services:

  database:
    image: 'postgres:bookworm'
    ports:
      - 5455:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mosip123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  config-server:
    image: mosipid/config-server:latest
    container_name: my_config_server
    ports:
      - "51000:51000"
    volumes:
      - <ABSOLUTE_PATH_TO_MOSIP_CONFIG>:/mosip-config   # host path : container path, provide absolute path of host, no change of container path
    environment:
       # Spring profile & config location
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:/mosip-config
      - SPRING_CLOUD_CONFIG_SERVER_ACCEPT_EMPTY=true
      - SPRING_CLOUD_CONFIG_SERVER_GIT_FORCE_PULL=false
      - SPRING_CLOUD_CONFIG_SERVER_GIT_CLONEONSTART=false
      - SPRING_CLOUD_CONFIG_SERVER_GIT_REFRESHRATE=0
      - SERVER_PORT=51000
      # Expose all actuator endpoints
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always
      # Disable security if the image has spring-security on classpath
      - MANAGEMENT_SECURITY_ENABLED=false
      - SPRING_SECURITY_ENABLED=false

  mock-service:
    image: wiremock/wiremock:latest
    container_name: master_data_mock_service
    ports:
      - "8082:8082"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings   # stub JSON files
      - ./wiremock/__files:/home/wiremock/__files
    command: --verbose --port 8082 --local-response-templating --max-template-cache-entries 10 --no-request-journal
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8082/__admin/health || exit 1"]
      interval: 500s
      timeout: 5s
      retries: 5
      start_period: 10s

  biosdk-service:
    image: mosipid/biosdk-server:1.3.0
    container_name: biosdk_service
    ports:
      - "8083:9099"
    environment:
      biosdk_zip_file_path: http://mock-service:8082/downloads/mock-sdk.zip
      biosdk_bioapi_impl: io.mosip.mock.sdk.impl.SampleSDKV2
    depends_on:
      mock-service:
        condition: service_healthy   # waits until wiremock is fully up


