\c mosip_ida

\ir ddl/ida-auth_transaction.sql
\ir ddl/ida-uin_auth_lock.sql
\ir ddl/ida-uin_hash_salt.sql
\ir ddl/ida-key_alias.sql
\ir ddl/ida-key_store.sql
\ir ddl/ida-key_policy_def.sql
\ir ddl/ida-key_policy_def_h.sql
\ir ddl/ida-identity_cache.sql
\ir ddl/ida-data_encrypt_keystore.sql
\ir ddl/ida-otp_transaction.sql
\ir ddl/ida-ca_cert_store.sql
\ir ddl/ida-credential_event_store.sql
\ir ddl/ida-hotlist_cache.sql
\ir ddl/ida-batch_job_execution.sql
\ir ddl/ida-batch_job_execution_context.sql
\ir ddl/ida-batch_job_execution_params.sql
\ir ddl/ida-batch_job_instance.sql
\ir ddl/ida-batch_step_execution.sql
\ir ddl/ida-batch_step_execution_context.sql
\ir ddl/ida-fk.sql
\ir ddl/ida-api_key_data.sql
\ir ddl/ida-partner_data.sql
\ir ddl/ida-partner_mapping.sql
\ir ddl/ida-policy_data.sql
\ir ddl/ida-misp_license_data.sql
\ir ddl/ida-anonymous_profile.sql
\ir ddl/ida-ident_binding_cert_store.sql
\ir ddl/ida-kyc_token_store.sql
\ir ddl/ida-oidc_client_data.sql
\ir ddl/ida-cred_subject_id_store.sql