\c mosip_ida 

GRANT CONNECT
   ON DATABASE mosip_ida
   TO idauser;

GRANT USAGE
   ON SCHEMA ida
   TO idauser;

GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES
   ON ALL TABLES IN SCHEMA ida
   TO idauser;

ALTER DEFAULT PRIVILEGES IN SCHEMA ida 
	GRANT SELECT,INSERT,UPDATE,DELETE,REFERENCES ON TABLES TO idauser;

