## End point(s) relative URLs
encryptionPath=v1/identity/encrypt?isInternal=false
internalEncryptionPath=v1/identity/encrypt?isInternal=true
encodePath=v1/identity/encode
decodePath=v1/identity/decode
decryptPath=/idauthentication/v1/internal/decrypt
encodeFilePath=v1/identity/encodeFile
decodeFilePath=v1/identity/decodeFile/?fileName=cbeff
validateSignaturePath=v1/identity/validateSign?signature=$signature$
splitEncryptedData=v1/identity/splitEncryptedData
bioValueEncryptionTemplate=config/bioValueEncryptionTemplate.json
idaMappingPath=config/mapping.properties
getIdaCertificateUrl=/idauthentication/v1/internal/getCertificate
putPartnerRegistrationUrl=/v1/partnermanager/partners
uploadCACertificateUrl=/v1/partnermanager/partners/certificate/ca/upload
uploadIntermediateCertificateUrl=/v1/partnermanager/partners/certificate/ca/upload
uploadPartnerCertificateUrl=/v1/partnermanager/partners/certificate/upload
masterSchemaURL=/v1/masterdata/idschema/latest
uploadIdaFirurl=v1/identity/uploadIDACertificate?certificateType=IDA_FIR&moduleName=$MODULENAME$&certsDir=$CERTSDIR$
uploadPartnerurl=v1/identity/uploadIDACertificate?certificateType=PARTNER&moduleName=$MODULENAME$&certsDir=$CERTSDIR$
uploadInternalurl=v1/identity/uploadIDACertificate?certificateType=INTERNAL&moduleName=$MODULENAME$&certsDir=$CERTSDIR$
authPolicyUrl=/v1/policymanager/policies
policyGroupUrl=/v1/policymanager/policies/group/new
publishPolicyurl=/v1/policymanager/policies/POLICYID/group/POLICYGROUPID/publish
fetchLocationData=/v1/masterdata/locations/all
generateArgon2HashURL=/v1/keymanager/generateArgon2Hash

## As below are non changble values, move these out from properties file
appIdForCertificate=IDA
partnerrefId=PARTNER
internalrefId=INTERNAL
idaFirRefId=IDA-FIR

#partner certificate refId, used for getting the partner certificate
uinGenMaxLoopCount=20
uinGenDelayTime=10000
Delaytime=90000
expireOtpTime=180000

## As these will be based on regEx, move these out from proprties file
passwordForAddIdentity=12341234_Aa
passwordToReset=12341234_AaB