#---------------------------------- Modifiable Properties ----------------------------------------------------------#

#------------------------ Environment URLs and Database Connections ------------------------#

# Keycloak URL.
keycloak-external-url = https://iam.qa21.mosip.net

# PostgreSQL URLs for audit and partner databases.
audit_url = jdbc:postgresql://qa21.mosip.net:5433/mosip_audit
partner_url = jdbc:postgresql://qa21.mosip.net:5433/mosip_ida

# Database server for connections.
db-server = api-internal.qa21.mosip.net
db-port=5433

#------------------------ secrets and passwords  ------------------------#

#------------------------ Keycloak Passwords ------------------------#
# Used for Keycloak authentication.
keycloak_Password = RBv3SFBz0y

#------------------------ PostgreSQL Database Passwords ------------------------#
# Credentials for connecting to Postgres databases.
audit_password =
partner_password =
postgres-password = &&4&1jeMG@j6MG9q

#-------- Client Secret Keys ----------#
# These keys are used for various services, make sure to update the values as required when running locally.

mosip_partner_client_secret =
mosip_pms_client_secret = fkbGLGHngSBxiPiO
mosip_resident_client_secret = tygESPaqk0TcQSex
mosip_idrepo_client_secret = J7tM4m9L0Ab3dcNf
mosip_reg_client_secret = ZSdIhu1fnrdNR1OX
mosip_admin_client_secret = nvM53Xsdp2wQdjNF
mosip_hotlist_client_secret = Ssm3tBCmlCVwjT9e
mosip_regproc_client_secret = RczqJoCJxiASXsCl
mpartner_default_mobile_secret = MVc0GappcSAZ4yjd
mosip_testrig_client_secret = o1tPpozjAFtxN0hI
AuthClientSecret =
mosip_crvs1_client_secret =



#-------- Generic Configuration ----------#

# Enable or disable debugging mode (yes/no).
enableDebug = yes

# Mock Notification Channels (email/phone/email,phone).
mockNotificationChannel = email,phone



#------------------------ Mosip Components Base URLs ------------------------#
# Define base URLs for different components if required.
# Example:
# mosip_components_base_urls = auditmanager=api-internal.released.mosip.net;idrepository=api-internal.released.mosip.net;authmanager=api-internal.released.mosip.net;resident=api-internal.released.mosip.net;partnermanager=api-internal.released.mosip.net;idauthentication=api-internal.released.mosip.net;masterdata=api-internal.released.mosip.net;idgenerator=api-internal.released.mosip.net;policymanager=api-internal.released.mosip.net;preregistration=api-internal.released.mosip.net;keymanager=api-internal.released.mosip.net;mock-identity-system=api.released.mosip.net
# Feel free to add more components as needed.
mosip_components_base_urls = idrepository=api-internal.qa21.mosip.net;idauthentication=api-internal.qa21.mosip.net;masterdata=api-internal.qa21.mosip.net;idgenerator=api-internal.qa21.mosip.net;authmanager=api-internal.qa21.mosip.net;auditmanager=api-internal.qa21.mosip.net;resident=api-internal.qa21.mosip.net;keymanager=api-internal.qa21.mosip.net

#------------------------ Module Name Pattern ------------------------#
# Define module name pattern if required.
# Example:
# moduleNamePattern = (mimoto|resident)
# Feel free to add more values as needed.
moduleNamePattern =



#------------------------ Uncomment for Local Run ------------------------#

# Path to the authentication certificates (if running locally, uncomment the below line and keep the value empty).
# authCertsPath =

# X-XSS-Protection: Controls the XSS (Cross-Site Scripting) filter in browsers.
# Values: (yes/no)
xssProtectionCheck = no

# Uncomment below line for generate dependency JSON. This works only in case of local run using IDE.
#generateDependencyJson = yes
# For selecting specific test cases to execute, provide comma separated values of test case unique identifiers
testCasesToExecute =

# Flag to generate dependency JSON (yes/no). This works only for local runs using an IDE
generateDependencyJson = no

# Maximum number of retry attempts for UIN availability check during OTP generation
uinGenMaxLoopCount= 20
uinGenDelayTime= 10000

# Wait time (in milliseconds) after UIN generation in IDREPO before proceeding
uinGenerationProcessingDelayTimeInMilliSeconds = 90000

# Wait time (in milliseconds) after VID generation in Resident before proceeding
vidGenerationProcessingDelayTimeInMilliSeconds = 90000

# Watchdog timeout in minutes (max execution time before forced termination)
watchdogTimeoutMinutes = 120