package io.mosip.registration.processor.core.constant;

public enum PacketFiles {
	BIOMETRIC, DEMOGRAPHIC, APPLICANT, INTRODUCER, LEFTEYE, LEFTPALM, RIGHTEYE, RIGHTPALM, BOTHTHUMBS, REGISTRATIONACKNOWLEDGEMENT, PROOFOFADDRESS, DEMOGRAPHICINFO, LEFTTHUMB, RIGHTTHUMB, APPLICANTPHOTO, EXCEPTIONPHOTO, PROOFOFIDENTITY, PACKETMETAINFO, OFFICERID, OFFICERFINGERPRINTIMAGE, OFFICERFINGERPRINTTYPE, OFFICERIRISIMAGE, OFFICERIRISTYPE, OFFICERAUTHENTICATIONIMAGE, OFFICERPIN, SUPERVISORID, SUPERVISORFINGERPRINTIMAGE, SUPERVISORFINGERPRINTTYPE, SUPERVISORIRISIMAGE, SUPERVISORIRISTYPE, SUPERVISORAUTHENTICATIONIMAGE, SUPERVISORPIN, INTRODUCERUIN, FACE, FINGER, IRIS, LEFTLITTLE, RIGHTLITTLE, LEFTMIDDLE, RIGHTMIDDLE, LEFTRING, RIGHTRING, RIGHTINDEX, LEFTINDEX, APPLICANTBIOMETRICSEQUENCE, INTRODUCERBIOMETRICSEQUENCE, APPLICANTDEMOGRAPHICSEQUENCE, INTRODUCERFINGERPRINTYPE, INTRODUCERIRISTYPE
}
