//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.13 at 03:22:53 PM IST 
//


package io.mosip.kernel.core.cbeffutil.jaxbclasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QualityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QualityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Algorithm" type="{http://standards.iso.org/iso-iec/19785/-3/ed-2/}RegistryIDType"/>
 *         &lt;choice>
 *           &lt;element name="Score" type="{http://standards.iso.org/iso-iec/19785/-3/ed-2/}QualityScoreType"/>
 *           &lt;element name="QualityCalculationFailed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QualityType", propOrder = {
    "algorithm",
    "score",
    "qualityCalculationFailed"
})
public class QualityType {

    @XmlElement(name = "Algorithm", required = true)
    protected RegistryIDType algorithm;
    @XmlElement(name = "Score")
    @XmlSchemaType(name = "unsignedInt")
    protected Long score;
    @XmlElement(name = "QualityCalculationFailed")
    protected String qualityCalculationFailed;

    /**
     * Gets the value of the algorithm property.
     * 
     * @return
     *     possible object is
     *     {@link RegistryIDType }
     *     
     */
    public RegistryIDType getAlgorithm() {
        return algorithm;
    }

    /**
     * Sets the value of the algorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegistryIDType }
     *     
     */
    public void setAlgorithm(RegistryIDType value) {
        this.algorithm = value;
    }

    /**
     * Gets the value of the score property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getScore() {
        return score;
    }

    /**
     * Sets the value of the score property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setScore(Long value) {
        this.score = value;
    }

    /**
     * Gets the value of the qualityCalculationFailed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualityCalculationFailed() {
        return qualityCalculationFailed;
    }

    /**
     * Sets the value of the qualityCalculationFailed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualityCalculationFailed(String value) {
        this.qualityCalculationFailed = value;
    }

}
