\c mosip_reg sysadmin

\ir ddl/reg-app_authentication_method.sql
\ir ddl/reg-biometric_attribute.sql
\ir ddl/reg-biometric_type.sql
\ir ddl/reg-blacklisted_words.sql
\ir ddl/reg-device_master.sql
\ir ddl/reg-device_spec.sql
\ir ddl/reg-device_type.sql
\ir ddl/reg-doc_category.sql
\ir ddl/reg-doc_type.sql
\ir ddl/reg-gender.sql
\ir ddl/reg-id_type.sql
\ir ddl/reg-key_store_DRBY.sql
\ir ddl/reg-language.sql
\ir ddl/reg-location.sql
\ir ddl/reg-machine_master.sql
\ir ddl/reg-machine_spec.sql
\ir ddl/reg-machine_type.sql
\ir ddl/reg-pre_registration_list.sql
\ir ddl/reg-reason_category.sql
\ir ddl/reg-reason_list.sql
\ir ddl/reg-registration.sql
\ir ddl/reg-registration_center.sql
\ir ddl/reg-registration_transaction.sql
\ir ddl/reg-reg_center_device.sql
\ir ddl/reg-reg_center_machine.sql
\ir ddl/reg-reg_center_machine_device.sql
\ir ddl/reg-reg_center_type.sql
\ir ddl/reg-reg_center_user.sql
\ir ddl/reg-reg_center_user_machine.sql
\ir ddl/reg-role_list.sql
\ir ddl/reg-screen_authorization.sql
\ir ddl/reg-sync_control.sql
\ir ddl/reg-sync_job_def.sql
\ir ddl/reg-sync_transaction.sql
\ir ddl/reg-template.sql
\ir ddl/reg-template_type.sql
\ir ddl/reg-title.sql
\ir ddl/reg-transaction_type.sql
\ir ddl/reg-user_biometric_DRBY.sql
\ir ddl/reg-user_detail.sql
\ir ddl/reg-user_pwd.sql
\ir ddl/reg-user_role.sql
\ir ddl/reg-valid_document.sql

\ir ddl/AlterFK_reg_schema.sql
