package io.mosip.preregistration.documents.code;

/**
 * 
 * Various Status codes for Document status table.
 * @author M1043008
 *
 */
public enum StatusCodes {

	DOCUMENT_FOR_VIRUS_SCAN,
	DOCUMENT_UPLOADED_TO_DATABASE,
	DOCUMENT_EXCEEDING_PERMITTED_SIZE,
	DOCUMENT_NOT_PRESENT_REQUEST,
	FILE_TYPE_NOT_SUPPORTED,
	DOCUMENT_INVALID_FORMAT,
	DOCUMENT_IS_MISSING,
	DOCUMENT_DELETE_SUCCESSFUL,
	DOCUMENT_TABLE_NOTACCESSIBLE 

}
