INSERT INTO master.reason_list(code,name,descr,rsncat_code,lang_code,is_active,cr_by,cr_dtimes ) VALUES ('APM','Age-Photo Mismatch','Mismatch between the Age and Photo','CLR','eng',true,'superadmin',now())
, ('GPM','Gender-Photo Mismatch','Gender-Photo Mismatch between Gender and Photo ','CLR','eng',true,'superadmin',now())
, ('IAD','Invalid Address','Invalid Address found','CLR','eng',true,'superadmin',now())
, ('DPG','Duplicate Registration','Duplicate Registration found','CLR','eng',true,'superadmin',now())
, ('OTH','Others','Others','CLR','eng',true,'superadmin',now())
, ('ADM','All the Details are matching','All the Details are matching','MNA','eng',true,'superadmin',now())
, ('ADD','All the Demographic Details are Matching','All the Demographic Details are Matching','MNA','eng',true,'superadmin',now())
, ('OPM','Only the Photograph is Matching','Only the Photograph is Matching','MNA','eng',true,'superadmin',now())
, ('SDM','Some of the Demographic Details are Matching','Some of the Demographic Details are Matching','MNA','eng',true,'superadmin',now())
, ('APM','عدم تطابق العمر-صور','حدث عدم تطابق بين العمر وصور','CLR','ara',true,'superadmin',now())
, ('GPM','عدم تطابق نوع الجنس-صور','عدم تطابق نوع الجنس-صور بين الجنسين وصور ','CLR','ara',true,'superadmin',now())
, ('IAD','عنوان غير صالح','يتم العثور على عنوان غير صالح','CLR','ara',true,'superadmin',now())
, ('DPG','تسجيل مكرر','تكرار التسجيل العثور على','CLR','ara',true,'superadmin',now())
, ('OTH','الآخرين','الآخرين','CLR','ara',true,'superadmin',now())
, ('ADM','يتم مطابقة جميع التفاصيل','يتم مطابقة جميع التفاصيل','MNA','ara',true,'superadmin',now())
, ('ADD','جميع تفاصيل ديموغرافية هي مطابقة','جميع تفاصيل ديموغرافية هي مطابقة','MNA','ara',true,'superadmin',now())
, ('OPM','إلا الصورة هي مطابقة','إلا الصورة هي مطابقة','MNA','ara',true,'superadmin',now())
, ('SDM','بعض التفاصيل الديمغرافية هي مطابقة','بعض التفاصيل الديمغرافية هي مطابقة','MNA','ara',true,'superadmin',now())
, ('APM','Décalage de lâge-Photo','Discordance entre lâge et la Photo','CLR','fra',true,'superadmin',now())
, ('GPM','Incompatibilité de sexe-Photo','Sexe-Photo discordance entre le sexe et la Photo ','CLR','fra',true,'superadmin',now())
, ('IAD','Adresse non valide','Adresse non valide trouvée','CLR','fra',true,'superadmin',now())
, ('DPG','Enregistrement en double','Double enregistrement trouvé','CLR','fra',true,'superadmin',now())
, ('OTH','Dautres','Dautres','CLR','fra',true,'superadmin',now())
, ('ADM','Tous les détails sont adaptent','Tous les détails sont adaptent','MNA','fra',true,'superadmin',now())
, ('ADD','Tous les détails démographiques sont Matching','Tous les détails démographiques sont Matching','MNA','fra',true,'superadmin',now())
, ('OPM','La photographie est le rapprochement','La photographie est le rapprochement','MNA','fra',true,'superadmin',now())
, ('SDM','Certains détails démographiques sont Matching','Certains détails démographiques sont Matching','MNA','fra',true,'superadmin',now());
