INSERT INTO master.id_type(code,name,descr,lang_code,is_active,cr_by,cr_dtimes ) VALUES ('UIN','Unique Identification Number','National ID given to the applicant','eng',true,'superadmin',now())
,('PRID','Pre-registration ID','ID assigned after Pre-registration','eng',true,'superadmin',now())
,('RID','Registration ID','ID assigned after registration','eng',true,'superadmin',now())
,('VID','Virtual ID','ID used in replacement of UIN','eng',true,'superadmin',now())
,('Token ID','Token ID','ID used by a vendor for an applicant','eng',true,'superadmin',now())
,('UIN','رقم تعريف فريد','الهوية الوطنية المقدمة لمقدم الطلب','ara',true,'superadmin',now())
,('PRID','رقم التسجيل المسبق','الرقم التعريفي بعد التسجيل المسبق','ara',true,'superadmin',now())
,('RID','معرف تسجيل','الرقم التعريفي بعد التسجيل','ara',true,'superadmin',now())
,('VID','معرف الظاهري','معرف يستخدم في استبدال الهوية الوطنية','ara',true,'superadmin',now())
,('Token ID','معرف الرمز المميز','معرف يستخدمه أحد البائعين لمقدم الطلب','ara',true,'superadmin',now())
,('UIN','Numéro didentification unique','Carte didentité nationale fournie au demandeur','fra',true,'superadmin',now())
,('PRID','ID de pré-inscription','ID attribué après la pré-inscription','fra',true,'superadmin',now())
,('RID','ID denregistrement','ID attribué après lenregistrement','fra',true,'superadmin',now())
,('VID','ID virtuel','Identifiant utilisé en remplacement de UIN','fra',true,'superadmin',now())
,('Token ID','ID de jeton','ID utilisé par un fournisseur pour un demandeur','fra',true,'superadmin',now());
