INSERT INTO master.template_type(code,descr,lang_code,is_active,cr_by,cr_dtimes ) VALUES ('auth-email-content','Template for authorization content','eng',true,'superadmin',now())
, ('auth-email-subject','Template for authorization subject','eng',true,'superadmin',now())
, ('auth-sms','Template for authorization SMS','eng',true,'superadmin',now())
, ('otp-email-content','Template for Email Content','eng',true,'superadmin',now())
, ('otp-email-subject','Template for Email Subject','eng',true,'superadmin',now())
, ('otp-sms','Template for OTP in SMS ','eng',true,'superadmin',now())
, ('auth-email-content','قالب لمحتوى التخويل','ara',true,'superadmin',now())
, ('auth-email-subject','قالب لموضوع التخويل','ara',true,'superadmin',now())
, ('auth-sms','قالب لرسالة التفويض','ara',true,'superadmin',now())
, ('otp-email-content','قالب لمحتوى البريد الإلكتروني','ara',true,'superadmin',now())
, ('otp-email-subject','قالب لموضوع البريد الإلكتروني','ara',true,'superadmin',now())
, ('otp-sms','قالب كلمة المرور لمرة واحدة في الرسالة','ara',true,'superadmin',now())
, ('auth-email-content','Modèle de contenu dautorisation','fra',true,'superadmin',now())
, ('auth-email-subject','Modèle pour sujet dautorisation','fra',true,'superadmin',now())
, ('auth-sms','Modèle de SMS dautorisation','fra',true,'superadmin',now())
, ('otp-email-content','Modèle de contenu de courrier électronique','fra',true,'superadmin',now())
, ('otp-email-subject','Modèle pour sujet demail','fra',true,'superadmin',now())
, ('otp-sms','Modèle pour OTP dans SMS','fra',true,'superadmin',now())
, ('RPR_DUP_UIN_EMAIL','Template for duplicate UIN Email','eng',true,'superadmin',now())
, ('RPR_DUP_UIN_SMS','Template for duplicate UIN SMS','eng',true,'superadmin',now())
, ('RPR_TEC_ISSUE_EMAIL','Template for Technical Issue Email','eng',true,'superadmin',now())
, ('RPR_TEC_ISSUE_SMS','Template for Technical Issue SMS','eng',true,'superadmin',now())
, ('RPR_UIN_GEN_EMAIL','Template for UIN generation Email','eng',true,'superadmin',now())
, ('RPR_UIN_GEN_SMS','Template for UIN generation SMS','eng',true,'superadmin',now())
, ('RPR_UIN_UPD_EMAIL','Template for update details Email','eng',true,'superadmin',now())
, ('RPR_UIN_UPD_SMS','Template for update Details SMS','eng',true,'superadmin',now())
, ('RPR_DUP_UIN_EMAIL','قالب لبريد إلكتروني مكرر الهوية','ara',true,'superadmin',now())
, ('RPR_DUP_UIN_SMS','قالب لرسالة الهوية المكررة','ara',true,'superadmin',now())
, ('RPR_TEC_ISSUE_EMAIL','نموذج للبريد الإلكتروني لمشكلة فنية','ara',true,'superadmin',now())
, ('RPR_TEC_ISSUE_SMS','قالب لرسالة المشكلة الفنية','ara',true,'superadmin',now())
, ('RPR_UIN_GEN_EMAIL','قالب لتوليد الهوية البريد الإلكتروني','ara',true,'superadmin',now())
, ('RPR_UIN_GEN_SMS','قالب لرسالة توليد الهوية','ara',true,'superadmin',now())
, ('RPR_UIN_UPD_EMAIL','قالب للحصول على تفاصيل التحديث','ara',true,'superadmin',now())
, ('RPR_UIN_UPD_SMS','قالب لتحديث تفاصيل الرسالة','ara',true,'superadmin',now())
, ('RPR_DUP_UIN_EMAIL','Modèle de courrier didentité en double','fra',true,'superadmin',now())
, ('RPR_DUP_UIN_SMS','Modèle de message didentité en double','fra',true,'superadmin',now())
, ('RPR_TEC_ISSUE_EMAIL','Modèle pour courrier électronique de problème technique','fra',true,'superadmin',now())
, ('RPR_TEC_ISSUE_SMS','Modèle de message de problème technique','fra',true,'superadmin',now())
, ('RPR_UIN_GEN_EMAIL','Modèle de courrier électronique de génération didentité','fra',true,'superadmin',now())
, ('RPR_UIN_GEN_SMS','Modèle de message de génération didentité','fra',true,'superadmin',now())
, ('RPR_UIN_UPD_EMAIL','Modèle pour les détails de la mise à jour Email','fra',true,'superadmin',now())
, ('RPR_UIN_UPD_SMS','Modèle pour la mise à jour Détails Message','fra',true,'superadmin',now())
, ('NewReg-email-content-template','Template for new registration Email Content','eng',true,'superadmin',now())
, ('NewReg-email-subject-template','Template for new registration Email Subject','eng',true,'superadmin',now())
, ('NewReg-sms-template','Template for new registration SMS','eng',true,'superadmin',now())
, ('OTP-email-content-template','Template for OTP generation Email Content','eng',true,'superadmin',now())
, ('OTP-email-subject-template','Template for OTP generation Email Subject','eng',true,'superadmin',now())
, ('OTP-sms-template','Template for OTP SMS','eng',true,'superadmin',now())
, ('Update-email-content-template','Template for update registration Email Content','eng',true,'superadmin',now())
, ('Update-email-subject-template','Template for update registration Email Subject','eng',true,'superadmin',now())
, ('Update-sms-template','Template for update registration SMS','eng',true,'superadmin',now())
, ('NewReg-email-content-template','قالب للتسجيل الجديد محتوى البريد الإلكتروني','ara',true,'superadmin',now())
, ('NewReg-email-subject-template','قالب للتسجيل الجديد البريد الإلكتروني الموضوع','ara',true,'superadmin',now())
, ('NewReg-sms-template','قالب لرسالة التسجيل الجديدة','ara',true,'superadmin',now())
, ('OTP-email-content-template','قالب لتوليد OTP محتوى البريد الإلكتروني','ara',true,'superadmin',now())
, ('OTP-email-subject-template','قالب لتوليد OTP البريد الإلكتروني الموضوع','ara',true,'superadmin',now())
, ('OTP-sms-template','قالب لرسالة OTP','ara',true,'superadmin',now())
, ('Update-email-content-template','قالب لتحديث تسجيل محتوى البريد الإلكتروني','ara',true,'superadmin',now())
, ('Update-email-subject-template','قالب لتسجيل التحديث البريد الإلكتروني الموضوع','ara',true,'superadmin',now())
, ('Update-sms-template','قالب لرسالة تسجيل التحديث','ara',true,'superadmin',now())
, ('NewReg-email-content-template','Modèle pour nouvelle inscription Email Content','fra',true,'superadmin',now())
, ('NewReg-email-subject-template','Modèle pour nouvelle inscription Objet de le-mail','fra',true,'superadmin',now())
, ('NewReg-sms-template','Modèle de nouvelle inscription SMS','fra',true,'superadmin',now())
, ('OTP-email-content-template','Modèle de contenu de courrier électronique de génération dOTP','fra',true,'superadmin',now())
, ('OTP-email-subject-template','Modèle pour le sujet de-mail de génération dOTP','fra',true,'superadmin',now())
, ('OTP-sms-template','Modèle pour SMS OTP','fra',true,'superadmin',now())
, ('Update-email-content-template','Modèle pour lenregistrement de la mise à jour','fra',true,'superadmin',now())
, ('Update-email-subject-template','Modèle denregistrement de mise à jour Objet de le-mail','fra',true,'superadmin',now())
, ('Update-sms-template','Modèle pour SMS denregistrement de mise à jour','fra',true,'superadmin',now())
, ('Email-Acknowledgement','Template for Email Acknowledgement','eng',true,'superadmin',now())
, ('Onscreen-Acknowledgement','Template for Onscreen Acknowledgment','eng',true,'superadmin',now())
, ('otp-email-content-template','Template for OTP Email Content','eng',true,'superadmin',now())
, ('otp-email-subject-template','Template for OTP Email Subject','eng',true,'superadmin',now())
, ('otp-sms-template','Template for OTP SMS','eng',true,'superadmin',now())
, ('SMS-Acknowledgement','Template for SMS Acknowledgement','eng',true,'superadmin',now())
, ('Email-Acknowledgement','قالب لتأكيد البريد الإلكتروني','ara',true,'superadmin',now())
, ('Onscreen-Acknowledgement','قالب للشاشة شكر وتقدير','ara',true,'superadmin',now())
, ('otp-email-content-template','قالب لمحتوى البريد الإلكتروني OTP','ara',true,'superadmin',now())
, ('otp-email-subject-template','قالب لموضوع البريد الإلكتروني OTP','ara',true,'superadmin',now())
, ('otp-sms-template','قالب ل OTP SMS','ara',true,'superadmin',now())
, ('SMS-Acknowledgement','قالب للإشعار SMS','ara',true,'superadmin',now())
, ('Email-Acknowledgement','Template for email confirmation','fra',true,'superadmin',now())
, ('Onscreen-Acknowledgement','On-screen recognition template','fra',true,'superadmin',now())
, ('otp-email-content-template','OTP Email Content Template','fra',true,'superadmin',now())
, ('otp-email-subject-template','Template for OTP email subject','fra',true,'superadmin',now())
, ('otp-sms-template','Template for OTP SMS','fra',true,'superadmin',now())
, ('SMS-Acknowledgement','Template for SMS Acknowledgment','fra',true,'superadmin',now())
, ('Acknowledgement-email-subject','Template for email subject of Acknowledgement','eng',true,'superadmin',now())
, ('Acknowledgement-email-subject','Modèle pour le sujet d`email d`accusé de réception','fra',true,'superadmin',now())
, ('Acknowledgement-email-subject','قالب للتسليم البريد الكتروني الموضوع','ara',true,'superadmin',now());
