INSERT INTO master.location(code,name,hierarchy_level,hierarchy_level_name,parent_loc_code,lang_code,is_active,cr_by,cr_dtimes ) VALUES ('MOR','Morroco','0','Country','','eng',true,'superadmin',now())
, ('MOR','الْـمَغْرِبُ','0','بلد','','ara',true,'superadmin',now())
, ('MOR','Maroc','0','Pays','','fra',true,'superadmin',now())
, ('RSK','Rabat Sale Kenitra','1','Region','MOR','eng',true,'superadmin',now())
, ('RSK','جهة الرباط سلا القنيطرة','1','منطقة','MOR','ara',true,'superadmin',now())
, ('RSK','Rabat-Salé-Kénitra','1','Région','MOR','fra',true,'superadmin',now())
, ('KTA','Kenitra','2','Province','RSK','eng',true,'superadmin',now())
, ('KTA','القنيطرة','2','المحافظة','RSK','ara',true,'superadmin',now())
, ('KTA','Kénitra','2','Province','RSK','fra',true,'superadmin',now())
, ('KNT','Kenitra','3','City','KTA','eng',true,'superadmin',now())
, ('KNT','القنيطرة','3','مدينة','KTA','ara',true,'superadmin',now())
, ('KNT','Kénitra','3','Ville','KTA','fra',true,'superadmin',now())
, ('BNMR','Ben Mansour','4','Local Administrative Authority','KNT','eng',true,'superadmin',now())
, ('BNMR','بن منصور','4','الهيئة الإدارية المحلية','KNT','ara',true,'superadmin',now())
, ('BNMR','Ben Mansour','4','Autorité administrative locale','KNT','fra',true,'superadmin',now())
, ('14022','14022','5','Postal Code','BNMR','eng',true,'superadmin',now())
, ('14022','14022','5','الرمز البريدي','BNMR','ara',true,'superadmin',now())
, ('14022','14022','5','code postal','BNMR','fra',true,'superadmin',now())
, ('MNAS','Mnasra','4','Local Administrative Authority','KNT','eng',true,'superadmin',now())
, ('MNAS','منَسرَ ','4','الهيئة الإدارية المحلية','KNT','ara',true,'superadmin',now())
, ('MNAS','Mnasra','4','Autorité administrative locale','KNT','fra',true,'superadmin',now())
, ('14053','14053','5','Postal Code','MNAS','eng',true,'superadmin',now())
, ('14053','14053','5','الرمز البريدي','MNAS','ara',true,'superadmin',now())
, ('14053','14053','5','code postal','MNAS','fra',true,'superadmin',now())
, ('MOGR','Mograne','4','Local Administrative Authority','KNT','eng',true,'superadmin',now())
, ('MOGR','مڭرن','4','الهيئة الإدارية المحلية','KNT','ara',true,'superadmin',now())
, ('MOGR','Mograne','4','Autorité administrative locale','KNT','fra',true,'superadmin',now())
, ('14023','14023','5','Postal Code','MOGR','eng',true,'superadmin',now())
, ('14023','14023','5','الرمز البريدي','MOGR','ara',true,'superadmin',now())
, ('14023','14023','5','code postal','MOGR','fra',true,'superadmin',now())
, ('ASSM','Assam','4','Local Administrative Authority','KNT','eng',true,'superadmin',now())
, ('ASSM','العصام','4','الهيئة الإدارية المحلية','KNT','ara',true,'superadmin',now())
, ('ASSM','Assam','4','Autorité administrative locale','KNT','fra',true,'superadmin',now())
, ('14000','14000','5','Postal Code','ASSM','eng',true,'superadmin',now())
, ('14000','14000','5','الرمز البريدي','ASSM','ara',true,'superadmin',now())
, ('14000','14000','5','code postal','ASSM','fra',true,'superadmin',now())
, ('MEHD','Mehdia','4','Local Administrative Authority','KNT','eng',true,'superadmin',now())
, ('MEHD','مهدية','4','الهيئة الإدارية المحلية','KNT','ara',true,'superadmin',now())
, ('MEHD','Mehdia','4','Autorité administrative locale','KNT','fra',true,'superadmin',now())
, ('14110','14110','5','Postal Code','MEHD','eng',true,'superadmin',now())
, ('14110','14110','5','الرمز البريدي','MEHD','ara',true,'superadmin',now())
, ('14110','14110','5','code postal','MEHD','fra',true,'superadmin',now())
, ('OLOJ','Ouled Oujih','4','Local Administrative Authority','KNT','eng',true,'superadmin',now())
, ('OLOJ','اولاد اوجيه','4','الهيئة الإدارية المحلية','KNT','ara',true,'superadmin',now())
, ('OLOJ','Ouled Oujih','4','Autorité administrative locale','KNT','fra',true,'superadmin',now())
, ('14080','14080','5','Postal Code','OLOJ','eng',true,'superadmin',now())
, ('14080','14080','5','الرمز البريدي','OLOJ','ara',true,'superadmin',now())
, ('14080','14080','5','code postal','OLOJ','fra',true,'superadmin',now())
, ('SDTB','Sidi Taibi','4','Local Administrative Authority','KNT','eng',true,'superadmin',now())
, ('SDTB','سيدي الطيبي','4','الهيئة الإدارية المحلية','KNT','ara',true,'superadmin',now())
, ('SDTB','Sidi Taibi','4','Autorité administrative locale','KNT','fra',true,'superadmin',now())
, ('14025','14025','5','Postal Code','SDTB','eng',true,'superadmin',now())
, ('14025','14025','5','الرمز البريدي','SDTB','ara',true,'superadmin',now())
, ('14025','14025','5','code postal','SDTB','fra',true,'superadmin',now())
, ('SATZ','Sidi Allal Tazi','4','Local Administrative Authority','KNT','eng',true,'superadmin',now())
, ('SATZ','علال التازي','4','الهيئة الإدارية المحلية','KNT','ara',true,'superadmin',now())
, ('SATZ','Sidi Allal Tazi','4','Autorité administrative locale','KNT','fra',true,'superadmin',now())
, ('14050','14050','5','Postal Code','SATZ','eng',true,'superadmin',now())
, ('14050','14050','5','الرمز البريدي','SATZ','ara',true,'superadmin',now())
, ('14050','14050','5','code postal','SATZ','fra',true,'superadmin',now())
, ('RBT','Rabat','2','Province','RSK','eng',true,'superadmin',now())
, ('RBT','الرباط','2','المحافظة','RSK','ara',true,'superadmin',now())
, ('RBT','Rabat','2','Province','RSK','fra',true,'superadmin',now())
, ('RAB','Rabat','3','City','RBT','eng',true,'superadmin',now())
, ('RAB','الرباط','3','مدينة','RBT','ara',true,'superadmin',now())
, ('RAB','Rabat','3','Ville','RBT','fra',true,'superadmin',now())
, ('AGDL','Agdal','4','Local Administrative Authority','RAB','eng',true,'superadmin',now())
, ('AGDL','أكدال','4','الهيئة الإدارية المحلية','RAB','ara',true,'superadmin',now())
, ('AGDL','Agdal','4','Autorité administrative locale','RAB','fra',true,'superadmin',now())
, ('10106','10106','5','Postal Code','AGDL','eng',true,'superadmin',now())
, ('10106','10106','5','الرمز البريدي','AGDL','ara',true,'superadmin',now())
, ('10106','10106','5','code postal','AGDL','fra',true,'superadmin',now())
, ('QRHS','Quartier Hassan','4','Local Administrative Authority','RAB','eng',true,'superadmin',now())
, ('QRHS','حي حسان','4','الهيئة الإدارية المحلية','RAB','ara',true,'superadmin',now())
, ('QRHS','Quartier Hassan','4','Autorité administrative locale','RAB','fra',true,'superadmin',now())
, ('10000','10000','5','Postal Code','QRHS','eng',true,'superadmin',now())
, ('10000','10000','5','الرمز البريدي','QRHS','ara',true,'superadmin',now())
, ('10000','10000','5','code postal','QRHS','fra',true,'superadmin',now())
, ('SOUS','Souissi','4','Local Administrative Authority','RAB','eng',true,'superadmin',now())
, ('SOUS','السويسي','4','الهيئة الإدارية المحلية','RAB','ara',true,'superadmin',now())
, ('SOUS','Souissi','4','Autorité administrative locale','RAB','fra',true,'superadmin',now())
, ('10105','10105','5','Postal Code','SOUS','eng',true,'superadmin',now())
, ('10105','10105','5','الرمز البريدي','SOUS','ara',true,'superadmin',now())
, ('10105','10105','5','code postal','SOUS','fra',true,'superadmin',now())
, ('MADI','Madinat Al Irfane','4','Local Administrative Authority','RAB','eng',true,'superadmin',now())
, ('MADI','مدينة العرفان','4','الهيئة الإدارية المحلية','RAB','ara',true,'superadmin',now())
, ('MADI','Madinat Al Irfane','4','Autorité administrative locale','RAB','fra',true,'superadmin',now())
, ('10112','10112','5','Postal Code','MADI','eng',true,'superadmin',now())
, ('10112','10112','5','الرمز البريدي','MADI','ara',true,'superadmin',now())
, ('10112','10112','5','code postal','MADI','fra',true,'superadmin',now())
, ('HARD','Hay Riad','4','Local Administrative Authority','RAB','eng',true,'superadmin',now())
, ('HARD','حي الرياض','4','الهيئة الإدارية المحلية','RAB','ara',true,'superadmin',now())
, ('HARD','Hay Riad','4','Autorité administrative locale','RAB','fra',true,'superadmin',now())
, ('10104','10104','5','Postal Code','HARD','eng',true,'superadmin',now())
, ('10104','10104','5','الرمز البريدي','HARD','ara',true,'superadmin',now())
, ('10104','10104','5','code postal','HARD','fra',true,'superadmin',now())
, ('MDDR','Medina de Rabat','4','Local Administrative Authority','RAB','eng',true,'superadmin',now())
, ('MDDR','مدينة','4','الهيئة الإدارية المحلية','RAB','ara',true,'superadmin',now())
, ('MDDR','Médina de Rabat','4','Autorité administrative locale','RAB','fra',true,'superadmin',now())
, ('10036','10036','5','Postal Code','MDDR','eng',true,'superadmin',now())
, ('10036','10036','5','الرمز البريدي','MDDR','ara',true,'superadmin',now())
, ('10036','10036','5','code postal','MDDR','fra',true,'superadmin',now())
, ('ELYF','EL YOUSSOUFIA','4','Local Administrative Authority','RAB','eng',true,'superadmin',now())
, ('ELYF','اليوسفية','4','الهيئة الإدارية المحلية','RAB','ara',true,'superadmin',now())
, ('ELYF','EL YOUSSOUFIA','4','Autorité administrative locale','RAB','fra',true,'superadmin',now())
, ('10190','10190','5','Postal Code','ELYF','eng',true,'superadmin',now())
, ('10190','10190','5','الرمز البريدي','ELYF','ara',true,'superadmin',now())
, ('10190','10190','5','code postal','ELYF','fra',true,'superadmin',now());
