INSERT INTO master.location(code,name,hierarchy_level,hierarchy_level_name,parent_loc_code,lang_code,is_active,cr_by,cr_dtimes ) VALUES ('MOR','Morroco','0','Country','','eng',true,'superadmin',now())
, ('MOR','الْـمَغْرِبُ','0','بلد','','ara',true,'superadmin',now())
, ('MOR','Maroc','0','Pays','','fra',true,'superadmin',now())
, ('RSK','Rabat Sale Kenitra','1','Region','MOR','eng',true,'superadmin',now())
, ('RSK','جهة الرباط سلا القنيطرة','1','منطقة','MOR','ara',true,'superadmin',now())
, ('RSK','Rabat-Salé-Kénitra','1','Région','MOR','fra',true,'superadmin',now())
, ('KTA','Kenitra','2','Province','RSK','eng',true,'superadmin',now())
, ('KTA','القنيطرة','2','المحافظة','RSK','ara',true,'superadmin',now())
, ('KTA','Kénitra','2','Province','RSK','fra',true,'superadmin',now())
, ('BNMR','Ben Mansour','3','Local Administrative Authority','KTA','eng',true,'superadmin',now())
, ('BNMR','بن منصور','3','الهيئة الإدارية المحلية','KTA','ara',true,'superadmin',now())
, ('BNMR','Ben Mansour','3','Autorité administrative locale','KTA','fra',true,'superadmin',now())
, ('14022','14022','4','Postal Code','BNMR','eng',true,'superadmin',now())
, ('14022','14022','4','الرمز البريدي','BNMR','ara',true,'superadmin',now())
, ('14022','14022','4','code postal','BNMR','fra',true,'superadmin',now())
, ('MNAS','Mnasra','3','Local Administrative Authority','KTA','eng',true,'superadmin',now())
, ('MNAS','منَسرَ ','3','الهيئة الإدارية المحلية','KTA','ara',true,'superadmin',now())
, ('MNAS','Mnasra','3','Autorité administrative locale','KTA','fra',true,'superadmin',now())
, ('14053','14053','4','Postal Code','MNAS','eng',true,'superadmin',now())
, ('14053','14053','4','الرمز البريدي','MNAS','ara',true,'superadmin',now())
, ('14053','14053','4','code postal','MNAS','fra',true,'superadmin',now())
, ('MOGR','Mograne','3','Local Administrative Authority','KTA','eng',true,'superadmin',now())
, ('MOGR','مڭرن','3','الهيئة الإدارية المحلية','KTA','ara',true,'superadmin',now())
, ('MOGR','Mograne','3','Autorité administrative locale','KTA','fra',true,'superadmin',now())
, ('14023','14023','4','Postal Code','MOGR','eng',true,'superadmin',now())
, ('14023','14023','4','الرمز البريدي','MOGR','ara',true,'superadmin',now())
, ('14023','14023','4','code postal','MOGR','fra',true,'superadmin',now())
, ('ASSM','Assam','3','Local Administrative Authority','KTA','eng',true,'superadmin',now())
, ('ASSM','العصام','3','الهيئة الإدارية المحلية','KTA','ara',true,'superadmin',now())
, ('ASSM','Assam','3','Autorité administrative locale','KTA','fra',true,'superadmin',now())
, ('14000','14000','4','Postal Code','ASSM','eng',true,'superadmin',now())
, ('14000','14000','4','الرمز البريدي','ASSM','ara',true,'superadmin',now())
, ('14000','14000','4','code postal','ASSM','fra',true,'superadmin',now())
, ('MEHD','Mehdia','3','Local Administrative Authority','KTA','eng',true,'superadmin',now())
, ('MEHD','مهدية','3','الهيئة الإدارية المحلية','KTA','ara',true,'superadmin',now())
, ('MEHD','Mehdia','3','Autorité administrative locale','KTA','fra',true,'superadmin',now())
, ('14110','14110','4','Postal Code','MEHD','eng',true,'superadmin',now())
, ('14110','14110','4','الرمز البريدي','MEHD','ara',true,'superadmin',now())
, ('14110','14110','4','code postal','MEHD','fra',true,'superadmin',now())
, ('OLOJ','Ouled Oujih','3','Local Administrative Authority','KTA','eng',true,'superadmin',now())
, ('OLOJ','اولاد اوجيه','3','الهيئة الإدارية المحلية','KTA','ara',true,'superadmin',now())
, ('OLOJ','Ouled Oujih','3','Autorité administrative locale','KTA','fra',true,'superadmin',now())
, ('14080','14080','4','Postal Code','OLOJ','eng',true,'superadmin',now())
, ('14080','14080','4','الرمز البريدي','OLOJ','ara',true,'superadmin',now())
, ('14080','14080','4','code postal','OLOJ','fra',true,'superadmin',now())
, ('SDTB','Sidi Taibi','3','Local Administrative Authority','KTA','eng',true,'superadmin',now())
, ('SDTB','سيدي الطيبي','3','الهيئة الإدارية المحلية','KTA','ara',true,'superadmin',now())
, ('SDTB','Sidi Taibi','3','Autorité administrative locale','KTA','fra',true,'superadmin',now())
, ('14025','14025','4','Postal Code','SDTB','eng',true,'superadmin',now())
, ('14025','14025','4','الرمز البريدي','SDTB','ara',true,'superadmin',now())
, ('14025','14025','4','code postal','SDTB','fra',true,'superadmin',now())
, ('SATZ','Sidi Allal Tazi','3','Local Administrative Authority','KTA','eng',true,'superadmin',now())
, ('SATZ','علال التازي','3','الهيئة الإدارية المحلية','KTA','ara',true,'superadmin',now())
, ('SATZ','Sidi Allal Tazi','3','Autorité administrative locale','KTA','fra',true,'superadmin',now())
, ('14050','14050','4','Postal Code','SATZ','eng',true,'superadmin',now())
, ('14050','14050','4','الرمز البريدي','SATZ','ara',true,'superadmin',now())
, ('14050','14050','4','code postal','SATZ','fra',true,'superadmin',now())
, ('RBT','Rabat','2','Province','RSK','eng',true,'superadmin',now())
, ('RBT','الرباط','2','المحافظة','RSK','ara',true,'superadmin',now())
, ('RBT','Rabat','2','Province','RSK','fra',true,'superadmin',now())
, ('AGDL','Agdal','3','Local Administrative Authority','RBT','eng',true,'superadmin',now())
, ('AGDL','أكدال','3','الهيئة الإدارية المحلية','RBT','ara',true,'superadmin',now())
, ('AGDL','Agdal','3','Autorité administrative locale','RBT','fra',true,'superadmin',now())
, ('10106','10106','4','Postal Code','AGDL','eng',true,'superadmin',now())
, ('10106','10106','4','الرمز البريدي','AGDL','ara',true,'superadmin',now())
, ('10106','10106','4','code postal','AGDL','fra',true,'superadmin',now())
, ('QRHS','Quartier Hassan','3','Local Administrative Authority','RBT','eng',true,'superadmin',now())
, ('QRHS','حي حسان','3','الهيئة الإدارية المحلية','RBT','ara',true,'superadmin',now())
, ('QRHS','Quartier Hassan','3','Autorité administrative locale','RBT','fra',true,'superadmin',now())
, ('10000','10000','4','Postal Code','QRHS','eng',true,'superadmin',now())
, ('10000','10000','4','الرمز البريدي','QRHS','ara',true,'superadmin',now())
, ('10000','10000','4','code postal','QRHS','fra',true,'superadmin',now())
, ('SOUS','Souissi','3','Local Administrative Authority','RBT','eng',true,'superadmin',now())
, ('SOUS','السويسي','3','الهيئة الإدارية المحلية','RBT','ara',true,'superadmin',now())
, ('SOUS','Souissi','3','Autorité administrative locale','RBT','fra',true,'superadmin',now())
, ('10105','10105','4','Postal Code','SOUS','eng',true,'superadmin',now())
, ('10105','10105','4','الرمز البريدي','SOUS','ara',true,'superadmin',now())
, ('10105','10105','4','code postal','SOUS','fra',true,'superadmin',now())
, ('MADI','Madinat Al Irfane','3','Local Administrative Authority','RBT','eng',true,'superadmin',now())
, ('MADI','مدينة العرفان','3','الهيئة الإدارية المحلية','RBT','ara',true,'superadmin',now())
, ('MADI','Madinat Al Irfane','3','Autorité administrative locale','RBT','fra',true,'superadmin',now())
, ('10112','10112','4','Postal Code','MADI','eng',true,'superadmin',now())
, ('10112','10112','4','الرمز البريدي','MADI','ara',true,'superadmin',now())
, ('10112','10112','4','code postal','MADI','fra',true,'superadmin',now())
, ('HARD','Hay Riad','3','Local Administrative Authority','RBT','eng',true,'superadmin',now())
, ('HARD','حي الرياض','3','الهيئة الإدارية المحلية','RBT','ara',true,'superadmin',now())
, ('HARD','Hay Riad','3','Autorité administrative locale','RBT','fra',true,'superadmin',now())
, ('10104','10104','4','Postal Code','HARD','eng',true,'superadmin',now())
, ('10104','10104','4','الرمز البريدي','HARD','ara',true,'superadmin',now())
, ('10104','10104','4','code postal','HARD','fra',true,'superadmin',now())
, ('MDDR','Medina de Rabat','3','Local Administrative Authority','RBT','eng',true,'superadmin',now())
, ('MDDR','مدينة','3','الهيئة الإدارية المحلية','RBT','ara',true,'superadmin',now())
, ('MDDR','Médina de Rabat','3','Autorité administrative locale','RBT','fra',true,'superadmin',now())
, ('10036','10036','4','Postal Code','MDDR','eng',true,'superadmin',now())
, ('10036','10036','4','الرمز البريدي','MDDR','ara',true,'superadmin',now())
, ('10036','10036','4','code postal','MDDR','fra',true,'superadmin',now())
, ('ELYF','EL YOUSSOUFIA','3','Local Administrative Authority','RBT','eng',true,'superadmin',now())
, ('ELYF','اليوسفية','3','الهيئة الإدارية المحلية','RBT','ara',true,'superadmin',now())
, ('ELYF','EL YOUSSOUFIA','3','Autorité administrative locale','RBT','fra',true,'superadmin',now())
, ('10190','10190','4','Postal Code','ELYF','eng',true,'superadmin',now())
, ('10190','10190','4','الرمز البريدي','ELYF','ara',true,'superadmin',now())
, ('10190','10190','4','code postal','ELYF','fra',true,'superadmin',now());
