INSERT INTO master.device_type(code,name,descr,lang_code,is_active,cr_by,cr_dtimes ) VALUES ('FRS','Finger Print Scanner','For scanning fingerprints','eng',true,'superadmin',now())
, ('FRS','ماسح بصمة الأصبع','لمسح بصمات الأصابع','ara',true,'superadmin',now())
, ('FRS','Scanner dempreintes digitales','Scannez les empreintes digitales','fra',true,'superadmin',now())
, ('IRS','Iris Scanner','For scanning Iris','eng',true,'superadmin',now())
, ('IRS','ايريس الماسح الضوئي','لمسح القزحية','ara',true,'superadmin',now())
, ('IRS','Scanner dIris','Pour scanner liris','fra',true,'superadmin',now())
, ('CMR','Camera','For capturing photo','eng',true,'superadmin',now())
, ('CMR','الة تصوير','لالتقاط الصور','ara',true,'superadmin',now())
, ('CMR','Caméra','Pour capturer une photo','fra',true,'superadmin',now())
, ('SCN','Document Scanner','For scanning documents','eng',true,'superadmin',now())
, ('SCN','وثيقة الماسح الضوئي','لمسح المستندات ضوئيًا','ara',true,'superadmin',now())
, ('SCN','Scanner de documents','Pour numériser des documents','fra',true,'superadmin',now())
, ('PRT','Printer','For printing Documents','eng',true,'superadmin',now())
, ('PRT','طابعة','لطباعة الوثائق','ara',true,'superadmin',now())
, ('PRT','Imprimante','Pour imprimer des documents','fra',true,'superadmin',now());
