-- ------------------------------------------------------------------------------------------
-- Revoke script for Migrating Spring Batch version to 5.0 as part of Java 21 Migration.
-- ------------------------------------------------------------------------------------------

-- Dropping column 'CREATE_TIME' from BATCH_STEP_EXECUTION (No need for type and constraints in DROP statement)
ALTER TABLE BATCH_STEP_EXECUTION DROP COLUMN CREATE_TIME;

-- Modifying the 'START_TIME' column to allow NULL values
ALTER TABLE BATCH_STEP_EXECUTION ALTER COLUMN START_TIME DROP NOT NULL;

-- Adding new columns to BATCH_JOB_EXECUTION_PARAMS
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS ADD COLUMN DATE_VAL TIMESTAMP;
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS ADD COLUMN LONG_VAL BIGINT;
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS ADD COLUMN DOUBLE_VAL DOUBLE PRECISION;

-- Modifying 'TYPE_CD' to have VARCHAR(6) data type
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS ALTER COLUMN TYPE_CD TYPE VARCHAR(6);

-- Renaming 'PARAMETER_TYPE' column to 'TYPE_CD'
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS RENAME COLUMN PARAMETER_TYPE TO TYPE_CD;

-- Modifying 'KEY_NAME' to have VARCHAR(100) data type
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS ALTER COLUMN KEY_NAME TYPE VARCHAR(100);

-- Renaming 'PARAMETER_NAME' column to 'KEY_NAME'
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS RENAME COLUMN PARAMETER_NAME TO KEY_NAME;

-- Modifying 'STRING_VAL' to have VARCHAR(250) data type
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS ALTER COLUMN STRING_VAL TYPE VARCHAR(250);

-- Renaming 'PARAMETER_VALUE' column to 'STRING_VAL'
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS RENAME COLUMN PARAMETER_VALUE TO STRING_VAL;

-- Adding a new column 'JOB_CONFIGURATION_LOCATION' to BATCH_JOB_EXECUTION
ALTER TABLE BATCH_JOB_EXECUTION ADD COLUMN JOB_CONFIGURATION_LOCATION VARCHAR(255);

-- Dropping sequences (these statements are correct)
DROP SEQUENCE BATCH_STEP_EXECUTION_SEQ;
DROP SEQUENCE BATCH_JOB_EXECUTION_SEQ;
DROP SEQUENCE BATCH_JOB_SEQ;
