node {

 def branch = '0.13.0_Ashish'
 def projectToBuild = 'automationtests'
 stage('------- Checkout --------') {
  print "${params.Environment}"
  // Checkout only automation tests Module
  dir(branch) {
   checkout([$class: 'GitSCM',
    branches: [
     [name: branch]
    ],
    userRemoteConfigs: [
     [url: 'https://github.com/mosip/mosip', credentialsId: '4c9741a2-4c15-4aad-a13d-3a1206u05321']
    ],
    extensions: [

     [$class: 'SparseCheckoutPaths', sparseCheckoutPaths: [
      [$class: 'SparseCheckoutPath', path: '/'+projectToBuild + '/']
     ]]

    ],
   ])
  }
 }


stage ('---------- mvn-clean-test ---------------') {
	  dir(branch+"/"+projectToBuild)
  {
	sh '/usr/local/maven/bin/mvn clean install -Dmaven.test.failure.ignore=true -Denv.user=dev -Denv.endpoint=https://`${params.Environment}`.mosip.io -Denv.testLevel=smokeAndRegression'
			  
  }
  
  publishHTML(
   target:[
   allowMissing: false, 
   alwaysLinkToLastBuild: false, 
   keepAll: true, 
   reportDir: branch+"/"+projectToBuild+"/target/surefire-reports", 
   reportFiles: 'MOSIP_ModuleLevelAutoRun_TestNGReport.html', 
   reportName: 'HTML Report'
])
}
          recipients = "$env.AUTOMATION_TEST_RECIPIENT_LIST"
emailext ( 
	    attachmentsPattern:'**/surefire-reports/MOSIP_ModuleLevelAutoRun_TestNGReport.html',
	    subject: "MOSIP Jenkins Job $JOB_NAME with build no $BUILD_NUMBER'",
	    body: """<p>Check console output at <a href="$BUILD_URL">'${JOB_NAME}'</a></p>""",
	    to: "$recipients",
	    from: '"Jenkins" <info@mosip.io>'
	)


}
