package io.mosip.registration.processor.status.code;

/**
 * Valid Status codes for Registration status table.
 *
 */
public enum RegistrationStatusCode {

	PACKET_UPLOADED_TO_LANDING_ZONE, PACKET_UPLOADED_TO_VIRUS_SCAN, VIRUS_SCAN_FAILED, VIRUS_SCAN_SUCCESSFUL, PACKET_UPLOADED_TO_FILESYSTEM, DUPLICATE_PACKET_RECIEVED, INVALID_PACKET_FORMAT, PACKET_NOT_PRESENT_IN_REQUEST, PACKET_SIZE_GREATER_THAN_LIMIT, PACKET_DECRYPTION_SUCCESSFUL, PACKET_DECRYPTION_FAILED, FILE_VALIDATION_SUCCESSFULL, FILE_VALIDATION_FAILED

}
