package io.mosip.preregistration.batchjobservices.code;

/**
 * @author M1043008
 *
 */
public enum ErrorMessage {
	
	NO_PRE_REGISTRATION_ID_FOUND_TO_UPDATE_CONSUMED_STATUS,
	NO_PRE_REGISTRATION_ID_FOUND_TO_MOVE,
	NO_PRE_REGISTRATION_ID_FOUND_TO_UPDATE_EXPIRED_STATUS,
	DEMOGRAPHIC_TABLE_NOT_ACCESSIBLE,
	REG_APPOINTMENT_TABLE_NOT_ACCESSIBLE;
	

}
