package io.mosip.preregistration.transliteration.errorcode;

public enum ErrorMessage {
	
	TRANSLITRATION_FAILED,
	MANDATORY_FIELDS_NOT_FILLED,
	ILLEGAL_PARAM_FIELD,
	JSON_HTTP_REQUEST_EXCEPTION,
	PRE_REG_TRANSLITRATION_TABLE_NOT_ACCESSIBLE,
	JSON_PARSING_FAILED;

}
