package io.mosip.dbentity;

public enum StageValidtionStatusEnum {
	PACKET_UPLOADED_TO_VIRUS_SCAN,
	PACKET_UPLOAD_TO_VIRUS_SCAN_FAILED,
	VIRUS_SCAN_SUCCESSFUL,
	VIRUS_SCAN_FAILED,
	PACKET_UPLOADED_TO_FILESYSTEM,
	STRUCTURE_VALIDATION_SUCCESS,
	STRUCTURE_VALIDATION_FAILED,
	PACKET_OSI_VALIDATION_SUCCESS,
	PACKET_OSI_VALIDATION_FAILED,
	PACKET_DEMO_DEDUPE_SUCCESS,
	PACKET_DEMO_DEDUPE_FAILED,
	PACKET_BIO_DEDUPE_SUCCESS,
	PACKET_BIO_DEDUPE_FAILED,
	PACKET_UIN_UPDATION_SUCCESS,
	UIN_GENERATION_FAILED
}
