package io.mosip.testrig.apirig.auth.testscripts;

import java.util.List;
import java.util.Map;

import org.apache.log4j.Level;
import org.apache.log4j.Logger;
import org.json.JSONObject;
import org.testng.ITest;
import org.testng.ITestContext;
import org.testng.ITestResult;
import org.testng.Reporter;
import org.testng.annotations.AfterClass;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

import io.mosip.testrig.apirig.auth.utils.IdAuthConfigManager;
import io.mosip.testrig.apirig.auth.utils.IdAuthenticationUtil;
import io.mosip.testrig.apirig.dto.OutputValidationDto;
import io.mosip.testrig.apirig.dto.TestCaseDTO;
import io.mosip.testrig.apirig.testrunner.BaseTestCase;
import io.mosip.testrig.apirig.utils.AdminTestException;
import io.mosip.testrig.apirig.utils.AuthenticationTestException;
import io.mosip.testrig.apirig.utils.BioDataUtility;
import io.mosip.testrig.apirig.utils.EncryptionDecrptionUtil;
import io.mosip.testrig.apirig.utils.OutputValidationUtil;
import io.mosip.testrig.apirig.utils.PartnerRegistration;
import io.mosip.testrig.apirig.utils.ReportUtil;
import io.mosip.testrig.apirig.utils.SecurityXSSException;
import io.restassured.response.Response;

public class BioAuth extends IdAuthenticationUtil implements ITest {
	private static final Logger logger = Logger.getLogger(BioAuth.class);
	protected String testCaseName = "";
	public Response response = null;
	public Response newResponse = null;
	public boolean isInternal = false;
	public String idKeyName = null;
	
	private EncryptionDecrptionUtil encryptDecryptUtil = new EncryptionDecrptionUtil();
	private BioDataUtility bioDataUtil = new BioDataUtility();

	@BeforeClass
	public static void setLogLevel() {
		if (IdAuthConfigManager.IsDebugEnabled())
			logger.setLevel(Level.ALL);
		else
			logger.setLevel(Level.ERROR);
	}

	/**
	 * get current testcaseName
	 */
	@Override
	public String getTestName() {
		return testCaseName;
	}

	/**
	 * Data provider class provides test case list
	 * 
	 * @return object of data provider
	 */
	@DataProvider(name = "testcaselist")
	public Object[] getTestCaseList(ITestContext context) {
		String ymlFile = context.getCurrentXmlTest().getLocalParameters().get("ymlFile");
		idKeyName = context.getCurrentXmlTest().getLocalParameters().get("idKeyName");
		isInternal = Boolean.parseBoolean(context.getCurrentXmlTest().getLocalParameters().get("isInternal"));
		logger.info("Started executing yml: " + ymlFile);
		return getYmlTestData(ymlFile);
	}
	@Test(dataProvider = "testcaselist")
	public void test(TestCaseDTO testCaseDTO) throws AuthenticationTestException, AdminTestException, SecurityXSSException {
		testCaseName = testCaseDTO.getTestCaseName();
		testCaseName = IdAuthenticationUtil.isTestCaseValidForExecution(testCaseDTO);
	
		String partnerKeyUrl = PartnerRegistration.mispLicKey + "/" + PartnerRegistration.partnerId + "/" + PartnerRegistration.apiKey;
		
		String partialPartnerKeyUrl = PartnerRegistration.mispLicKey + "/" + PartnerRegistration.partnerId;
		
		String ekycPartnerKeyURL = PartnerRegistration.mispLicKey + "/" + PartnerRegistration.ekycPartnerId + "/" + PartnerRegistration.kycApiKey;
		
		if (testCaseDTO.getEndPoint().contains("$partnerKeyURL$")) {
			testCaseDTO.setEndPoint(testCaseDTO.getEndPoint().replace("$partnerKeyURL$", partnerKeyUrl));
			PartnerRegistration.appendEkycOrRp.set("rp-");
		}
		if (testCaseDTO.getEndPoint().contains("$partialPartnerKeyUrl$")) {
			testCaseDTO.setEndPoint(testCaseDTO.getEndPoint().replace("$partialPartnerKeyUrl$", partialPartnerKeyUrl));
			testCaseDTO.setEndPoint(replaceIdWithAutogeneratedId(testCaseDTO.getEndPoint(), "$ID:"));
			PartnerRegistration.appendEkycOrRp.set("rp-");
		}
		// Isolates only the IdP-LK (license key) segment as invalid, keeping the real partner ID, unlike $partialPartnerKeyUrl$'s dummy-both-segments variant
		if (testCaseDTO.getEndPoint().contains("$invalidLicenseKeyUrl$")) {
			testCaseDTO.setEndPoint(testCaseDTO.getEndPoint().replace("$invalidLicenseKeyUrl$",
					"invalid-license-key-0000" + "/" + PartnerRegistration.partnerId));
			testCaseDTO.setEndPoint(replaceIdWithAutogeneratedId(testCaseDTO.getEndPoint(), "$ID:"));
			PartnerRegistration.appendEkycOrRp.set("rp-");
		}
		// Isolates only the Auth-Partner-ID segment as invalid, keeping the real license key, unlike $partialPartnerKeyUrl$'s dummy-both-segments variant
		if (testCaseDTO.getEndPoint().contains("$invalidPartnerIdUrl$")) {
			testCaseDTO.setEndPoint(testCaseDTO.getEndPoint().replace("$invalidPartnerIdUrl$",
					PartnerRegistration.mispLicKey + "/" + "invalid-partner-id-0000"));
			testCaseDTO.setEndPoint(replaceIdWithAutogeneratedId(testCaseDTO.getEndPoint(), "$ID:"));
			PartnerRegistration.appendEkycOrRp.set("rp-");
		}
		if (testCaseDTO.getEndPoint().contains("$kycDelegationDisabledPartnerKeyUrl$")) {
			testCaseDTO.setEndPoint(testCaseDTO.getEndPoint().replace("$kycDelegationDisabledPartnerKeyUrl$",
					IdAuthenticationUtil.generateAndGetKycDelegationDisabledPartnerKeyUrl()));
			testCaseDTO.setEndPoint(replaceIdWithAutogeneratedId(testCaseDTO.getEndPoint(), "$ID:"));
			PartnerRegistration.appendEkycOrRp.set("rp-");
		}
		if (testCaseDTO.getEndPoint().contains("$ekycPartnerKeyURL$")) {
			testCaseDTO.setEndPoint(testCaseDTO.getEndPoint().replace("$ekycPartnerKeyURL$", ekycPartnerKeyURL));
			PartnerRegistration.appendEkycOrRp.set("ekyc-");
		}
		if (testCaseDTO.getEndPoint().contains("$UpdatedPartnerKeyURL$")) {
			testCaseDTO.setEndPoint(testCaseDTO.getEndPoint().replace("$UpdatedPartnerKeyURL$",
					PartnerRegistration.updatedpartnerKeyUrl));
		}
		
		JSONObject request = new JSONObject(testCaseDTO.getInput());
		String identityRequest = null, identityRequestTemplate = null, identityRequestEncUrl = null;
		if (request.has("identityRequest")) {
			identityRequest = request.get("identityRequest").toString();
			request.remove("identityRequest");
		}
		// env is otherwise unconditionally forced to "Staging" below (no YAML/keyword
		// hook existed before), matching the same override-hook pattern used for
		// thumbprint/requestHMAC/requestSessionKey in DemoAuth.java.
		String invalidEnv = null;
		if (request.has("invalidEnv")) {
			invalidEnv = request.getString("invalidEnv");
			request.remove("invalidEnv");
		}
		identityRequest = buildIdentityRequest(identityRequest);
		
		JSONObject identityReqJson = new JSONObject(identityRequest);
		identityRequestTemplate = identityReqJson.getString("identityRequestTemplate");
		identityReqJson.remove("identityRequestTemplate");
		identityRequestEncUrl = identityReqJson.getString("identityRequestEncUrl");
		identityReqJson.remove("identityRequestEncUrl");
		identityRequest = getJsonFromTemplate(identityReqJson.toString(), identityRequestTemplate);
		logger.info(identityRequest);
		if (identityRequest.contains("baseurl")) {
			String domainUrl =  BaseTestCase.ApplnURI;
			identityRequest = identityRequest.replace("baseurl", domainUrl);
		}
		if (identityRequest.contains("$DOMAINURI$")) {
			String domainUrl =  BaseTestCase.ApplnURI;
			identityRequest = identityRequest.replace("$DOMAINURI$", domainUrl);
		}
		logger.info(identityRequest);
		String encryptedIdentityReq = null;
		try {
			encryptedIdentityReq = bioDataUtil.constractBioIdentityRequest(identityRequest,
					getResourcePath() + props.getProperty("bioValueEncryptionTemplate"), testCaseName, isInternal);
			System.out.println("encryptedIdentityReq = " + encryptedIdentityReq);
		} catch (Exception e) {
			e.printStackTrace();
		}

		Map<String, String> bioAuthTempMap = (isInternal)
				? encryptDecryptUtil.getInternalEncryptSessionKeyValue(encryptedIdentityReq)
				: encryptDecryptUtil.getEncryptSessionKeyValue(encryptedIdentityReq);
		String authRequest = getJsonFromTemplate(request.toString(), testCaseDTO.getInputTemplate());
		logger.info("************* Modification of bio auth request ******************");
		Reporter.log("<b><u>Modification of bio auth request</u></b>");

		logger.info("authRequest is = " + authRequest);
		logger.info("bioAuthTempMap is = " + bioAuthTempMap);
		// modifyRequest unconditionally rewrites requestTime to the current
		// timestamp (see OtpAuthNew's identical save/restore), which silently
		// clobbers a YAML-hardcoded expired/malformed value - save it here and
		// restore it below so Expired/Malformed RequestTime negative tests still
		// send what the YAML actually specifies.
		String originalRequestTime = new JSONObject(authRequest).optString("requestTime", null);
		authRequest = modifyRequest(authRequest, bioAuthTempMap,
				getResourcePath() + props.getProperty("idaMappingPath"));
		logger.info("authRequestTemp is = " + authRequest);
		JSONObject authRequestTemp = new JSONObject(authRequest);
		if (originalRequestTime != null) {
			authRequestTemp.put("requestTime", originalRequestTime);
		}
		authRequestTemp.remove("env");
		authRequestTemp.put("env", invalidEnv != null ? invalidEnv : "Staging");
		authRequest = authRequestTemp.toString();
		testCaseDTO.setInput(authRequest);

		logger.info("******Post request Json to EndPointUrl: " + ApplnURI + testCaseDTO.getEndPoint() + " *******");

		// No YAML/keyword hook exists anywhere in the shared framework to omit or
		// corrupt the signature header (it is always computed unconditionally by
		// postRequestWithCookieAuthHeaderAndSignature) - this dedicated variant is
		// only used by the InvalidSignature negative test case.
		if (testCaseName.contains("_InvalidSignature_")) {
			response = postRequestWithCookieAuthHeaderAndCorruptSignature(ApplnURI + testCaseDTO.getEndPoint(),
					authRequest, COOKIENAME, testCaseDTO.getRole(), testCaseDTO.getTestCaseName());
		} else {
			response = postRequestWithCookieAuthHeaderAndSignature(ApplnURI + testCaseDTO.getEndPoint(), authRequest,
					COOKIENAME, testCaseDTO.getRole(), testCaseDTO.getTestCaseName());
		}

		if (testCaseName.toLowerCase().contains("_sid")) {
			writeAutoGeneratedId(response, idKeyName, testCaseName);
		}

		Map<String, List<OutputValidationDto>> ouputValid = OutputValidationUtil.doJsonOutputValidation(
				response.asString(), getJsonFromTemplate(testCaseDTO.getOutput(), testCaseDTO.getOutputTemplate()));
		Reporter.log(ReportUtil.getOutputValidationReport(ouputValid));

		if (!OutputValidationUtil.publishOutputResult(ouputValid))
			throw new AdminTestException("Failed at output validation");

		


	}

	/**
	 * The method ser current test name to result
	 * 
	 * @param result
	 */
	@AfterMethod(alwaysRun = true)
	public void setResultTestName(ITestResult result) {
		result.setAttribute("TestCaseName", testCaseName);

	}

	@AfterClass
	public static void authTestTearDown() {
	}
}
