package io.mosip.testrig.apirig.auth.testscripts;

import java.util.List;
import java.util.Map;

import org.apache.log4j.Level;
import org.apache.log4j.Logger;
import org.testng.ITest;
import org.testng.ITestContext;
import org.testng.ITestResult;
import org.testng.Reporter;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

import io.mosip.testrig.apirig.auth.utils.IdAuthConfigManager;
import io.mosip.testrig.apirig.auth.utils.IdAuthenticationUtil;
import io.mosip.testrig.apirig.dto.OutputValidationDto;
import io.mosip.testrig.apirig.dto.TestCaseDTO;
import io.mosip.testrig.apirig.utils.AdminTestException;
import io.mosip.testrig.apirig.utils.AuthenticationTestException;
import io.mosip.testrig.apirig.utils.OutputValidationUtil;
import io.mosip.testrig.apirig.utils.PartnerRegistration;
import io.mosip.testrig.apirig.utils.ReportUtil;
import io.mosip.testrig.apirig.utils.SecurityXSSException;
import io.restassured.response.Response;

public class KycExchange extends IdAuthenticationUtil implements ITest {
	private static final Logger logger = Logger.getLogger(KycExchange.class);
	protected String testCaseName = "";
	public Response response = null;
	public Response newResponse = null;
	public boolean isInternal = false;


	@BeforeClass
	public static void setLogLevel() {
		if (IdAuthConfigManager.IsDebugEnabled())
			logger.setLevel(Level.ALL);
		else
			logger.setLevel(Level.ERROR);
	}

	/**
	 * get current testcaseName
	 */
	@Override
	public String getTestName() {
		return testCaseName;
	}

	/**
	 * Data provider class provides test case list
	 * 
	 * @return object of data provider
	 */
	@DataProvider(name = "testcaselist")
	public Object[] getTestCaseList(ITestContext context) {
		String ymlFile = context.getCurrentXmlTest().getLocalParameters().get("ymlFile");
		isInternal = Boolean.parseBoolean(context.getCurrentXmlTest().getLocalParameters().get("isInternal"));
		logger.info("Started executing yml: " + ymlFile);
		return getYmlTestData(ymlFile);
	}

	@Test(dataProvider = "testcaselist")
	public void test(TestCaseDTO testCaseDTO)
			throws AuthenticationTestException, AdminTestException, SecurityXSSException {
		testCaseName = testCaseDTO.getTestCaseName();
		testCaseName = IdAuthenticationUtil.isTestCaseValidForExecution(testCaseDTO);

		String partnerKeyUrl = PartnerRegistration.mispLicKey + "/" + PartnerRegistration.partnerId + "/"
				+ PartnerRegistration.apiKey;

		String partialPartnerKeyUrl = PartnerRegistration.mispLicKey + "/" + PartnerRegistration.partnerId;

		String ekycPartnerKeyURL = PartnerRegistration.mispLicKey + "/" + PartnerRegistration.ekycPartnerId + "/"
				+ PartnerRegistration.kycApiKey;

		testCaseDTO.setEndPoint(uriKeyWordHandelerUri(testCaseDTO.getEndPoint(), testCaseName));
		PartnerRegistration.appendEkycOrRp.set("rp-");
		if (testCaseDTO.getEndPoint().contains("$partnerKeyURL$")) {
			testCaseDTO.setEndPoint(testCaseDTO.getEndPoint().replace("$partnerKeyURL$", partnerKeyUrl));
			PartnerRegistration.appendEkycOrRp.set("rp-");
		}
		if (testCaseDTO.getEndPoint().contains("$partialPartnerKeyUrl$")) {
			testCaseDTO.setEndPoint(testCaseDTO.getEndPoint().replace("$partialPartnerKeyUrl$", partialPartnerKeyUrl));
			testCaseDTO.setEndPoint(replaceIdWithAutogeneratedId(testCaseDTO.getEndPoint(), "$ID:"));

			PartnerRegistration.appendEkycOrRp.set("rp-");
		}
		// Isolates only the IdP-LK (license key) segment as invalid, keeping the real partner ID, unlike $partialPartnerKeyUrl$'s dummy-both-segments variant
		if (testCaseDTO.getEndPoint().contains("$invalidLicenseKeyUrl$")) {
			testCaseDTO.setEndPoint(testCaseDTO.getEndPoint().replace("$invalidLicenseKeyUrl$",
					"invalid-license-key-0000" + "/" + PartnerRegistration.partnerId));
			testCaseDTO.setEndPoint(replaceIdWithAutogeneratedId(testCaseDTO.getEndPoint(), "$ID:"));
			PartnerRegistration.appendEkycOrRp.set("rp-");
		}
		// Isolates only the Auth-Partner-ID segment as invalid, keeping the real license key, unlike $partialPartnerKeyUrl$'s dummy-both-segments variant
		if (testCaseDTO.getEndPoint().contains("$invalidPartnerIdUrl$")) {
			testCaseDTO.setEndPoint(testCaseDTO.getEndPoint().replace("$invalidPartnerIdUrl$",
					PartnerRegistration.mispLicKey + "/" + "invalid-partner-id-0000"));
			testCaseDTO.setEndPoint(replaceIdWithAutogeneratedId(testCaseDTO.getEndPoint(), "$ID:"));
			PartnerRegistration.appendEkycOrRp.set("rp-");
		}
		if (testCaseDTO.getEndPoint().contains("$kycDelegationDisabledPartnerKeyUrl$")) {
			testCaseDTO.setEndPoint(testCaseDTO.getEndPoint().replace("$kycDelegationDisabledPartnerKeyUrl$",
					IdAuthenticationUtil.generateAndGetKycDelegationDisabledPartnerKeyUrl()));
			testCaseDTO.setEndPoint(replaceIdWithAutogeneratedId(testCaseDTO.getEndPoint(), "$ID:"));
			PartnerRegistration.appendEkycOrRp.set("rp-");
		}
		if (testCaseDTO.getEndPoint().contains("$ekycPartnerKeyURL$")) {
			testCaseDTO.setEndPoint(testCaseDTO.getEndPoint().replace("$ekycPartnerKeyURL$", ekycPartnerKeyURL));
			PartnerRegistration.appendEkycOrRp.set("ekyc-");
		}
		if (testCaseDTO.getEndPoint().contains("$UpdatedPartnerKeyURL$")) {
			testCaseDTO.setEndPoint(testCaseDTO.getEndPoint().replace("$UpdatedPartnerKeyURL$",
					PartnerRegistration.updatedpartnerKeyUrl));
		}

		String inputJson = getJsonFromTemplate(testCaseDTO.getInput(), testCaseDTO.getInputTemplate());

		inputJson = IdAuthenticationUtil.inputStringKeyWordHandeler(inputJson, testCaseName);

		logger.info("******Post request Json to EndPointUrl: " + ApplnURI + testCaseDTO.getEndPoint() + " *******");

		// No YAML/keyword hook exists anywhere in the shared framework to omit or
		// corrupt the signature header (it is always computed unconditionally by
		// postRequestWithCookieAuthHeaderAndSignature) - these dedicated variants are
		// only used by the InvalidSignature/MissingSignature negative test cases.
		if (testCaseName.contains("_InvalidSignature_")) {
			response = postRequestWithCookieAuthHeaderAndCorruptSignature(ApplnURI + testCaseDTO.getEndPoint(),
					inputJson, COOKIENAME, testCaseDTO.getRole(), testCaseDTO.getTestCaseName());
		} else if (testCaseName.contains("_MissingSignature_")) {
			response = postRequestWithCookieAuthHeaderAndCorruptSignature(ApplnURI + testCaseDTO.getEndPoint(),
					inputJson, COOKIENAME, testCaseDTO.getRole(), testCaseDTO.getTestCaseName(), "");
		} else {
			response = postRequestWithCookieAuthHeaderAndSignature(ApplnURI + testCaseDTO.getEndPoint(), inputJson,
					COOKIENAME, testCaseDTO.getRole(), testCaseDTO.getTestCaseName());
		}

		String actualResponse = response.asString();
		// Dedicated decode tests only (name contains "_Decode_"): base64/JWE-decode
		// encryptedKyc and merge its claims into response.decodedKyc so the normal
		// YAML output assertion mechanism can reference them like any other field.
		// Never touches the response for the other ~26 kyc-exchange tests.
		if (testCaseName.contains("_Decode_")) {
			actualResponse = IdAuthenticationUtil.injectDecodedKyc(actualResponse, testCaseName);
		}
		// max_age-filtered scenario (TC_22): OutputValidationUtil's exact-match/$IGNORE$ model
		// can't express "this field must be absent" (a missing expected path is always a hard
		// failure there), so absence is asserted explicitly here instead of via the YAML output.
		if (testCaseName.contains("_MaxAgeFiltered_")) {
			IdAuthenticationUtil.assertVerifiedClaimAbsent(actualResponse, "email", testCaseName);
		}
		// requested-claim-not-available scenario (TC_28): same absence-assertion need as
		// _MaxAgeFiltered_ above, for a claim (fullName) the fixture identity has no real
		// verified data for at all, under any trust framework.
		if (testCaseName.contains("_ClaimNotAvailable_")) {
			IdAuthenticationUtil.assertVerifiedClaimAbsent(actualResponse, "fullName", testCaseName);
		}

		Map<String, List<OutputValidationDto>> ouputValid = OutputValidationUtil.doJsonOutputValidation(
				actualResponse, getJsonFromTemplate(testCaseDTO.getOutput(), testCaseDTO.getOutputTemplate()),
				testCaseDTO, response.getStatusCode());
		Reporter.log(ReportUtil.getOutputValidationReport(ouputValid));

		if (!OutputValidationUtil.publishOutputResult(ouputValid))
			throw new AdminTestException("Failed at output validation");

	}

	/**
	 * The method ser current test name to result
	 *
	 * @param result
	 */
	@AfterMethod(alwaysRun = true)
	public void setResultTestName(ITestResult result) {
		result.setAttribute("TestCaseName", testCaseName);

	}
}
