package io.mosip.registration.processor.filesystem.ceph.adapter.impl.utils;

public enum PacketFiles {
	BIOMETRIC, DEMOGRAPHIC, APPLICANT, INTRODUCER, LEFTEYE, LEFTPALM, RIGHTEYE, RIGHTPALM, BOTHTHUMBS, REGISTRATIONACKNOWLDEGEMENT, PROOFOFADDRESS, DEMOGRAPHICINFO, LEFTTHUMB, RIGHTTHUMB, APPLICANTPHOTO, APPLICANTEXCEPTIONPHOTO
}
