package io.mosip.preregistration.application.code;

/**
 * 
 * Various Status codes for Document status table.
 * 
 * @author M1043008
 *
 */
public enum StatusCodes {

	DOCUMENT_FOR_VIRUS_SCAN, 
	DOCUMENT_UPLOADED_TO_DATABASE, 
	DOCUMENT_EXCEEDING_PERMITTED_SIZE, 
	DOCUMENT_NOT_PRESENT_REQUEST, 
	FILE_TYPE_NOT_SUPPORTED, 
	DOCUMENT_INVALID_FORMAT, 
	DOCUMENT_DELETE_SUCCESSFUL, 
	DOCUMENT_FAILED_TO_DELETE, 
	RECORD_NOT_FOUND_EXCEPTION, 
	TABLE_NOT_ACCESSABLE, 
	JSON_VALIDATION_FAIL;
}
