-- create table section -----------------------------------------------------------
-- schema 		: idmap	- Id-Authentication 
-- table 		: vid	- Virtual ID for authentication
-- table alias  : vid

-- schemas section -----------------------------------------------------------------

-- create schema if idmap schema for Id-Authentication schema not exists
create schema if not exists idmap
;

-- table section --------------------------------------------------------------------
create table idmap.vid (
	id 	 character varying(36) not null,
	vid character varying(36) not null,
	uin_hash  character varying(128) not null,     		-- UIN of indivisuals and referenced from idrepo database 
	uin  character varying(500) not null,     		-- UIN of indivisuals and referenced from idrepo database 
	vidtyp_code character varying(36) not null,
	generated_dtimes timestamp not null,
	expiry_dtimes timestamp,
	status_code character varying(32) not null,
	cr_by 		character varying(256) not null,
	cr_dtimes 	timestamp  not null,
	upd_by  	character varying (256),
	upd_dtimes timestamp,
	is_deleted 	boolean,
	del_dtimes timestamp
)
;

-- keys section --------------------------------------------------------------------------
alter table idmap.vid add constraint pk_vid primary key (id)
 ;

-- indexes section ------------------------------------------------------------------------
-- create index idx_vid_<colX> on idmap.vid(ColX)
-- ;

-- comments section ------------------------------------------------------------------------ 
comment on table idmap.vid is 'To store generated list of Virtual IDs for Authentication'
;
comment on column idmap.vid.id is 'Unique id generated by the system for each of the vid generated'
;


alter table idmap.vid add constraint uk_vid unique (vid) ;

alter table idmap.vid add constraint uk_vid_uinhash unique (uin_hash, vidtyp_code, generated_dtimes) ;
