package io.mosip.registration.code;

public enum StatusCodes {
	
	DOCUMENT_FOR_VIRUS_SCAN,
	DOCUMENT_UPLOADED_TO_DATABASE,
	DOCUMENT_SIZE_GREATER_THAN_LIMIT,
	DOCUMENT_NOT_PRESENT_REQUEST,
	DOCUMENT_INVALID_FORMAT,
	TABLE_NOT_FOUND_EXCEPTION

}
