package io.mosip.registration.code;

public enum StatusCodes {

	DOCUMENT_FOR_VIRUS_SCAN, DOCUMENT_UPLOADED_TO_DATABASE, DOCUMENT_EXCEEDING_PERMITTED_SIZE, DOCUMENT_NOT_PRESENT_REQUEST, FILE_TYPE_NOT_SUPPORTED, DOCUMENT_INVALID_FORMAT

}
