#!/usr/bin/env bash

# regex to validate in commit msg
commit_regex='(^MOS-[0-9]+|^Merge|^merge)'
error_msg="Aborting commit. Your commit message should start with JIRA Issue like  MOS-1111 or 'merge'"
if ! grep -iqE "$commit_regex" "$1"; then
    echo "$error_msg" >&2
    exit 1
fi