package io.mosip.registration.processor.filesystem.ceph.adapter.impl.utils;

public enum PacketFiles {
	BIOMETRIC, DEMOGRAPHIC, APPLICANT, INTRODUCER, LEFTEYE, LEFTPALM, RIGHTEYE, RIGHTPALM, BOTHTHUMBS, REGISTRATIONACKNOWLEDGEMENT, PROOFOFADDRESS, DEMOGRAPHICINFO, LEFTTHUMB, RIGHTTHUMB, APPLICANTPHOTO, EXCEPTIONPHOTO, PROOFOFIDENTITY, PACKETMETAINFO, APPLICANTBIOMETRICSEQUENCE, INTRODUCERBIOMETRICSEQUENCE, APPLICANTDEMOGRAPHICSEQUENCE
}
