package io.mosip.registration.processor.filesystem.ceph.adapter.impl.utils;

public enum PacketFiles {
	BIOMETRIC, DEMOGRAPHIC, APPLICANT, INTRODUCER, LEFTEYE, LEFTPALM, RIGHTEYE, RIGHTPALM, BOTHTHUMBS, REGISTRATIONACKNOWLEDGEMENT, PROOFOFADDRESS, DEMOGRAPHICINFO, LEFTTHUMB, RIGHTTHUMB, APPLICANTPHOTO, EXCEPTIONPHOTO, PROOFOFIDENTITY, PACKETMETAINFO, OFFICERID, OFFICERFINGERPRINTIMAGE, OFFICERFINGERPRINTTYPE, OFFICERIRISIMAGE, OFFICERIRISTYPE, OFFICERAUTHENTICATIONIMAGE, OFFICERPIN, SUPERVISIORID, SUPERVISIORFINGERPRINTIMAGE, SUPERVISIORFINGERPRINTTYPE, SUPERVISIORIRISIMAGE, SUPERVISIORIRISTYPE, SUPERVISIORAUTHENTICATIONIMAGE, SUPERVISIORPIN, INTRODUCERUIN, FACE, FINGER, IRIS, LEFTLITTLE, RIGHTLITTLE, LEFTMIDDLE, RIGHTMIDDLE, LEFTRING, RIGHTRING, RIGHTINDEX, LEFTINDEX, APPLICANTBIOMETRICSEQUENCE, INTRODUCERBIOMETRICSEQUENCE, APPLICANTDEMOGRAPHICSEQUENCE
}
