INSERT INTO master.doc_type(code,name,descr,lang_code,is_active,cr_by,cr_dtimes) VALUES ('CIN','CNIE card','Moroccan National Electronic ID Card','eng',true,'superadmin',now())
, ('CIN','نَتِنَل ِد','بطاقة الهوية الوطنية المغربية','ara',true,'superadmin',now())
, ('CIN','carte didentité','Carte didentité électronique nationale marocaine','fra',true,'superadmin',now())
, ('RNC','Rental contract','Rental Agreement of address','eng',true,'superadmin',now())
, ('RNC','عقد ايجار','اتفاق تأجير العنوان','ara',true,'superadmin',now())
, ('RNC','Contrat de location','Contrat de location dadresse','fra',true,'superadmin',now())
, ('COR','Certificate of residence','Proof of Resident','eng',true,'superadmin',now())
, ('COR','شهادة الاقامة','اثبات محل الاقامة','ara',true,'superadmin',now())
, ('COR','Certificat de résidence','Preuve de résidence','fra',true,'superadmin',now())
, ('PSP','Passport','Proof of Idendity','eng',true,'superadmin',now())
, ('PSP','جواز سفر','إثبات الهوية','ara',true,'superadmin',now())
, ('PSP','Passeport','Preuve didentité','fra',true,'superadmin',now())
, ('CRN','Certificate of Relationship','Proof relationship of a person','eng',true,'superadmin',now())
, ('CRN','شهادة العلاقة','علاقة إثبات للشخص','ara',true,'superadmin',now())
, ('CRN','Certificat de relation','Preuve de relation dune personne','fra',true,'superadmin',now())
, ('COB','Certificate of Birth','Proof birth and age of a person','eng',true,'superadmin',now())
, ('COB','شهادة الميلاد','إثبات الولادة وعمر الشخص','ara',true,'superadmin',now())
, ('COB','Certificat de naissance','Preuve de naissance et âge dune personne','fra',true,'superadmin',now());
