INSERT INTO master.process_list(id,name,descr,lang_code,is_active,cr_by,cr_dtimes ) VALUES ('login_auth','Login authentication','Login authentication','eng',true,'superadmin',now())
, ('eod_auth','Eod authentication','Eod authentication','eng',true,'superadmin',now())
, ('packet_auth','Packet authentication','Packet authentication','eng',true,'superadmin',now())
, ('exception_auth','Exception authentication','Exception authentication','eng',true,'superadmin',now())
, ('onboard_auth','Onboard authentication','Onboard authentication','eng',true,'superadmin',now())
, ('login_auth','مصادقة تسجيل الدخول','مصادقة تسجيل الدخول','ara',true,'superadmin',now())
, ('eod_auth','التخلص من الذخائر المتفجرة المصادقة','التخلص من الذخائر المتفجرة المصادقة','ara',true,'superadmin',now())
, ('packet_auth','حزمة المصادقة','حزمة المصادقة','ara',true,'superadmin',now())
, ('exception_auth','استثناء المصادقة','استثناء المصادقة','ara',true,'superadmin',now())
, ('onboard_auth','مصادقة على متن الطائرة','مصادقة على متن الطائرة','ara',true,'superadmin',now())
, ('login_auth','Authentification de connexion','Authentification de connexion','fra',true,'superadmin',now())
, ('eod_auth','Authentification de nem','Authentification de nem','fra',true,'superadmin',now())
, ('packet_auth','Authentification de paquet','Authentification de paquet','fra',true,'superadmin',now())
, ('exception_auth','Authentification d’exception','Authentification d’exception','fra',true,'superadmin',now())
, ('onboard_auth','Authentification intégrée','Authentification intégrée','fra',true,'superadmin',now());
