INSERT INTO master.biometric_attribute(code,name,descr,bmtyp_code,lang_code,is_active,cr_by,cr_dtimes) VALUES ('LTM','Left Thumb','Print of Left Thumb','FNR','eng',true,'superadmin',now())
,('RTM','Right Thumb','Print of Right Thumb','FNR','eng',true,'superadmin',now())
,('LIF','Left Index Finger','Print of Left Index Finger','FNR','eng',true,'superadmin',now())
,('RIF','Right Index Finger','Print of Right Index Finger','FNR','eng',true,'superadmin',now())
,('LMF','Left Middle Finger','Print of Left Middle Finger','FNR','eng',true,'superadmin',now())
,('RMF','Right Middle Finger','Print of Right Middle Finger','FNR','eng',true,'superadmin',now())
,('LRF','Left Ring Finger','Print of Left Ring Finger','FNR','eng',true,'superadmin',now())
,('RRF','Right Ring Finger','Print of Right Ring Finger','FNR','eng',true,'superadmin',now())
,('LLF','Left Little Finger','Print of Left Little Finger','FNR','eng',true,'superadmin',now())
,('RLF','Right Little Finger','Print of Right Little Finger','FNR','eng',true,'superadmin',now())
,('LIR','Left Iris','Print of Left Iris','IRS','eng',true,'superadmin',now())
,('RIR','Right Iris','Print of Right Iris','IRS','eng',true,'superadmin',now())
,('PTT','Photo','Print of Photo','PHT','eng',true,'superadmin',now())
,('LTM','الإبهام الأيمن','طباعة إبهام الأيمن','FNR','ara',true,'superadmin',now())
,('RTM','الإبهام الأيمن','طباعة إبهام الأيمن','FNR','ara',true,'superadmin',now())
,('LIF','السبابة اليسرى','طباعة سبابة اليسرى','FNR','ara',true,'superadmin',now())
,('RIF','السبابة اليمنى','طباعة سبابة اليمنى','FNR','ara',true,'superadmin',now())
,('LMF','الإصبع الأوسط الأيسر','طباعة للاصبع الأوسط الأيسر','FNR','ara',true,'superadmin',now())
,('RMF','الإصبع الأوسط الأيمن','طباعة للاصبع الأوسط الأيمن','FNR','ara',true,'superadmin',now())
,('LRF','البنصر الأيسر','الطباعة من اليسار خاتم الإصبع','FNR','ara',true,'superadmin',now())
,('RRF','بنصر الحق','طباعة بنصر الحق','FNR','ara',true,'superadmin',now())
,('LLF','خنصر اليسرى','طباعة خنصر اليسرى','FNR','ara',true,'superadmin',now())
,('RLF','خنصر اليمنى','طباعة خنصر اليمنى','FNR','ara',true,'superadmin',now())
,('LIR','قزحية العين اليسرى','طباعة من قزحية العين اليسرى','IRS','ara',true,'superadmin',now())
,('RIR','قزحية العين اليمنى','طباعة قزحية الحق','IRS','ara',true,'superadmin',now())
,('PTT','صور','طباعة الصور','PHT','ara',true,'superadmin',now())
,('LTM','Pouce gauche','Impression du pouce gauche','FNR','fra',true,'superadmin',now())
,('RTM','Pouce droit','Impression de votre pouce droit','FNR','fra',true,'superadmin',now())
,('LIF','Index gauche','Impression de lindex gauche','FNR','fra',true,'superadmin',now())
,('RIF','Index droit','Impression de lindex droit','FNR','fra',true,'superadmin',now())
,('LMF','Doigt du milieu gauche','Impression du doigt du milieu gauche','FNR','fra',true,'superadmin',now())
,('RMF','Doigt du milieu droit','Impression du doigt du milieu droit','FNR','fra',true,'superadmin',now())
,('LRF','Annulaire gauche','Impression de lannulaire gauche','FNR','fra',true,'superadmin',now())
,('RRF','Annulaire droit','Impression de lannulaire droit','FNR','fra',true,'superadmin',now())
,('LLF','Auriculaire gauche','Impression de lauriculaire gauche','FNR','fra',true,'superadmin',now())
,('RLF','Bon petit doigt','Impression dauriculaire droite','FNR','fra',true,'superadmin',now())
,('LIR','Iris gauche','Impression de lIris gauche','IRS','fra',true,'superadmin',now())
,('RIR','Droit dIris','Impression dIris droite','IRS','fra',true,'superadmin',now())
,('PTT','Photo','Impression de Photo','PHT','fra',true,'superadmin',now());
