node {

 def server = Artifactory.server 'ART'
 def rtMaven = Artifactory.newMavenBuild()
 def buildInfo
 def branch = env.NEXT_BRANCH_NAME
 def dockerImagesTagVersion = branch  //This will ensure that docker images tag should have 1-1 relation ship with project version
 def projectToBuild = 'authentication'
 def registryUrl = 'http://docker-registry.mosip.io:5000'
 def registryName = 'docker-registry.mosip.io:5000'
 def registryCredentials = '305c7f35-2eb5-44b4-b574-a0855ef70c26'
 k8DevContext = 'dev-k8-cluster'
 updatedServices = []
 updatedDockerImages = []
 
 stage('------- Checkout --------') {
  // Checkout only Authentication Module
  dir(branch) {
   checkout([$class: 'GitSCM',
    branches: [
     [name: branch]
    ],
    userRemoteConfigs: [
     [url: 'https://github.com/mosip/mosip', credentialsId: '4c9741a2-4c15-4aad-a13d-3a1206u05321']
    ],
    extensions: [

     [$class: 'PathRestriction', excludedRegions: '', includedRegions: projectToBuild +'/.*'],
     [$class: 'SparseCheckoutPaths', sparseCheckoutPaths: [
      [$class: 'SparseCheckoutPath', path: '/'+projectToBuild + '/']
     ]]

    ],
   ])
  }
 }
 stage('--------- Artifactory configuration ----------------') {
  rtMaven.tool = 'M2_HOME' // Tool name from Jenkins configuration
  rtMaven.deployer releaseRepo: 'libs-release-local', snapshotRepo: 'libs-snapshot-local', server: server
  rtMaven.resolver releaseRepo: 'libs-release', snapshotRepo: 'libs-snapshot', server: server
  buildInfo = Artifactory.newBuildInfo()
  buildInfo.env.capture = true
 }

stage ('---------- mvn-clean-install ---------------') {
        rtMaven.run pom: branch + '/' + projectToBuild + '/pom.xml', goals: 'clean install -Dspring.cloud.config.label='+branch, buildInfo: buildInfo
}

stage('---------- SonarQube Analysis --------------') {
  def mvnHome = tool name: 'M2_HOME', type: 'maven'
  withSonarQubeEnv('sonar') {
   sh "${mvnHome}/bin/mvn -f '$branch/$projectToBuild/' sonar:sonar"
  }
 }

stage('----------- Publish build info -------------') {
  server.publishBuildInfo buildInfo
 }
 
stage('-----------Docker image push and cleanup-----------') {
	dir(branch) {
			sh "find . -name 'Dockerfile'> directoryDockerFiles"
			locationOfDockerFiles = readFile( "directoryDockerFiles" ).split( "\\r?\\n" );
			sh "rm -f directoryDockerFiles"
			for (int i=0; i < locationOfDockerFiles.size(); i++) {
			if(locationOfDockerFiles[i].equals("")){
			echo "No Dockerfile found"
			break;
			}
			echo locationOfDockerFiles[i]
			def currentModule = locationOfDockerFiles[i]
			sh "basename `dirname $currentModule` > parentDirectoryName"
			parentDirectoryName = readFile('parentDirectoryName').trim()
			sh "rm -f parentDirectoryName"
			sh "dirname $currentModule > parentDirectoryPath"
			parentDirectoryPath = readFile('parentDirectoryPath').trim()
			sh "rm -f parentDirectoryPath"
			docker.withRegistry(registryUrl,registryCredentials) {
			echo "$currentModule"
			echo "$parentDirectoryName"
			echo "$parentDirectoryPath"
			def buildName = "$parentDirectoryName:$dockerImagesTagVersion"
			newApp = docker.build(buildName, '--build-arg spring_config_label='+branch+'-f '+locationOfDockerFiles[i]+' '+parentDirectoryPath)
			    newApp.push()
			    newApp.push 'latest'
			 }
			sh "docker rmi $parentDirectoryName:$dockerImagesTagVersion"
			sh "docker rmi $registryName/$parentDirectoryName:$dockerImagesTagVersion"
			sh "docker rmi $registryName/$parentDirectoryName"

			}

	}


}

stage('Kubernetes Deploy : DEV-INT'){
      //this stage will rollout the changes on Kubernetes Cluster
      sh "kubectl config use-context $k8DevContext"
      sh " kubectl set image deployment/authentication-service authentication-service=docker-registry.mosip.io:5000/authentication-service:$dockerImagesTagVersion"
      echo "Getting list of all services" 
      sh "kubectl get pods"
    }
 

}
